/*
  JavaScript Flod 1.0
  2012/02/08
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
"use strict";window.neoart=Object.create(null);function ByteArray(b){var a=Object.create(null,{endian:{value:1,writable:!0},length:{value:0,writable:!0},index:{value:0,writable:!0},buffer:{value:null,writable:!0},view:{value:null,writable:!0},bytesAvailable:{get:function(){return this.length-this.index}},position:{get:function(){return this.index},set:function(a){0>a?a=0:a>this.length&&(a=this.length);this.index=a}},clear:{value:function(){this.buffer=new ArrayBuffer;this.view=null;this.index=this.length=0}},readAt:{value:function(a){return this.view.getUint8(a)}},
readByte:{value:function(){return this.view.getInt8(this.index++)}},readShort:{value:function(){var a=this.view.getInt16(this.index,this.endian);this.index+=2;return a}},readInt:{value:function(){var a=this.view.getInt32(this.index,this.endian);this.index+=4;return a}},readUbyte:{value:function(){return this.view.getUint8(this.index++)}},readUshort:{value:function(){var a=this.view.getUint16(this.index,this.endian);this.index+=2;return a}},readUint:{value:function(){var a=this.view.getUint32(this.index,
this.endian);this.index+=4;return a}},readBytes:{value:function(a,b,d){var a=a.view,c=this.index,e=this.view;if((d+=c)>this.length)d=this.length;for(;c<d;++c)a.setUint8(b++,e.getUint8(c))}},readString:{value:function(a){var b=this.index,d=this.view,c="";if((a+=b)>this.length)a=this.length;for(;b<a;++b)c+=String.fromCharCode(d.getUint8(b));this.index=a;return c}},writeAt:{value:function(a,b){this.view.setUint8(a,b)}},writeByte:{value:function(a){this.view.setInt8(this.index++,a)}},writeShort:{value:function(a){this.view.setInt16(this.index,
a);this.index+=2}},writeInt:{value:function(a){this.view.setInt32(this.index,a);this.index+=4}}});a.buffer=b;a.view=new DataView(b);a.length=b.byteLength;return Object.seal(a)}function Sample(){return Object.create(null,{l:{value:0,writable:!0},r:{value:0,writable:!0},next:{value:null,writable:!0}})}
function CoreMixer(){return Object.create(null,{player:{value:null,writable:!0},channels:{value:[],writable:!0},buffer:{value:[],writable:!0},samplesTick:{value:0,writable:!0},samplesLeft:{value:0,writable:!0},remains:{value:0,writable:!0},completed:{value:0,writable:!0},bufferSize:{get:function(){return this.buffer.length},set:function(b){var a;a=this.buffer.length||0;if(!(b==a||512>b))if(this.buffer.length=b,b>a){this.buffer[a]=Sample();for(a=++a;a<b;++a)this.buffer[a]=this.buffer[a-1].next=Sample()}}},
complete:{get:function(){return this.completed},set:function(b){this.completed=b^this.player.loopSong}},reset:{value:function(){var b=this.channels[0],a=this.buffer[0];for(this.completed=this.remains=this.samplesLeft=0;b;)b.initialize(),b=b.next;for(;a;)a.l=a.r=0,a=a.next}},restore:{configurable:!0,value:function(){}}})}
function CorePlayer(){var b=Object.create(null,{context:{value:null,writable:!0},node:{value:null,writable:!0},analyse:{value:0,writable:!0},endian:{value:0,writable:!0},sampleRate:{value:0,writable:!0},playSong:{value:0,writable:!0},lastSong:{value:0,writable:!0},version:{value:0,writable:!0},title:{value:"",writable:!0},channels:{value:0,writable:!0},loopSong:{value:0,writable:!0},speed:{value:0,writable:!0},tempo:{value:0,writable:!0},mixer:{value:null,writable:!0},tick:{value:0,writable:!0},paused:{value:0,
writable:!0},callback:{value:null,writable:!0},quality:{configurable:!0,set:function(a){this.callback=a?this.mixer.accurate.bind(this.mixer):this.mixer.fast.bind(this.mixer)}},toggle:{value:function(a){this.mixer.channels[a].mute^=1}},setup:{configurable:!0,value:function(){}},load:{value:function(a){this.lastSong=this.playSong=this.version=0;this.mixer.restore();a.view||(a=ByteArray(a));a.position=0;if(67324752==a.readUint())if(window.neoart.Unzip)a=ZipFile(a),a=a.uncompress(a.entries[0]);else throw"Unzip support is not available.";
a.endian=this.endian;a.position=0;this.loader(a);this.version&&this.setup();return this.version}},play:{value:function(){var a;this.version&&(this.paused?this.paused=0:(this.initialize(),this.node=this.context.createJavaScriptNode(this.mixer.bufferSize),this.node.onaudioprocess=this.callback),this.analyse&&window.neoart.Flectrum?(a=window.neoart.analyserNode=this.context.createAnalyser(),this.node.connect(a),a.connect(this.context.destination)):this.node.connect(this.context.destination),a=document.createEvent("Event"),
a.initEvent("flodPlay",!0,!1),document.dispatchEvent(a))}},pause:{value:function(){if(this.node){this.node.disconnect();this.paused=1;var a=document.createEvent("Event");a.initEvent("flodPause",!0,!1);document.dispatchEvent(a)}}},stop:{value:function(){if(this.node){this.node.disconnect();this.node.onaudioprocess=this.node=null;this.paused=0;var a=document.createEvent("Event");a.initEvent("flodStop",!0,!1);document.dispatchEvent(a)}}},reset:{value:function(){this.tick=0;this.mixer.initialize();this.mixer.samplesTick=
2.5*this.sampleRate/this.tempo>>0}}});window.neoart.audioContext||(window.neoart.audioContext=new webkitAudioContext);b.context=window.neoart.audioContext;b.sampleRate=b.context.sampleRate;return b};