/*
  JavaScript Flod 1.0
  2011/11/30
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
"use strict";window.neoart=Object.create(null);function createByteArray(b){var a=Object.create(null,{buffer:{value:null,writable:!0},view:{value:null,writable:!0},endian:{value:1,writable:!0},length:{value:0,writable:!0},currpos:{value:0,writable:!0},bytesAvailable:{get:function(){return this.length-this.currpos}},position:{get:function(){return this.currpos},set:function(a){if(0>a)a=0;else if(a>this.length)a=this.length;this.currpos=a}},readByte:{value:function(){var a=this.view.getInt8(this.currpos);this.currpos++;return a}},readShort:{value:function(){var a=
this.view.getInt16(this.currpos,this.endian);this.currpos+=2;return a}},readInt:{value:function(){var a=this.view.getInt32(this.currpos,this.endian);this.currpos+=4;return a}},readUnsignedByte:{value:function(){var a=this.view.getUint8(this.currpos);this.currpos++;return a}},readUnsignedShort:{value:function(){var a=this.view.getUint16(this.currpos,this.endian);this.currpos+=2;return a}},readUnsignedInt:{value:function(){var a=this.view.getUint32(this.currpos,this.endian);this.currpos+=4;return a}},
readBytes:{value:function(a,b,c){var d=this.currpos,c=c+d;if(c>this.length)c=this.length;for(;d<c;++d)a.setInt8(b++,this.view.getInt8(d))}},readString:{value:function(a){for(var b=this.currpos,c="",a=a+this.currpos;b<a;++b)c+=String.fromCharCode(this.view.getUint8(b));this.currpos=a;return c}},writeByte:{value:function(a){this.view.setInt8(this.currpos,a);this.currpos++}},writeInt:{value:function(a){this.view.setInt32(this.currpos,a,this.endian);this.currpos+=4}}});a.buffer=b;a.view=new DataView(b);
a.length=b.byteLength;return Object.seal(a)}function createSample(){return Object.create(null,{l:{value:0,writable:!0},r:{value:0,writable:!0},next:{value:null,writable:!0}})}
function createCoreMixer(){return Object.create(null,{player:{value:null,writable:!0},channels:{value:[],writable:!0},buffer:{value:[],writable:!0},samplesTick:{value:0,writable:!0},samplesLeft:{value:0,writable:!0},completed:{value:0,writable:!0},remains:{value:0,writable:!0},bufferSize:{get:function(){return this.buffer.length},set:function(b){var a;a=this.buffer.length||0;if(b!=a&&(this.buffer.length=b,b>a)){this.buffer[a]=createSample();for(a=++a;a<b;++a)this.buffer[a]=this.buffer[a-1].next=createSample()}}},
complete:{get:function(){return this.completed},set:function(b){this.completed=b^this.player.loopSong}},core_initialize:{value:function(){var b=this.channels[0],a=this.buffer[0];for(this.samplesLeft=this.remains=this.completed=0;b;)b.initialize(),b=b.next;for(;a;)a.l=a.r=0,a=a.next}},reset:{configurable:!0,value:function(){}}})}
function createCorePlayer(){var b=Object.create(null,{context:{value:null,writable:!0},node:{value:null,writable:!0},analyse:{value:0,writable:!0},sampleRate:{value:0,writable:!0},version:{value:0,writable:!0},title:{value:"",writable:!0},channels:{value:0,writable:!0},loopSong:{value:0,writable:!0},speed:{value:0,writable:!0},tempo:{value:0,writable:!0},mixer:{value:null,writable:!0},tick:{value:0,writable:!0},timer:{value:0,writable:!0},endian:{value:0,writable:!0},paused:{value:0,writable:!0},
callback:{value:null,writable:!0},quality:{configurable:!0,set:function(a){this.callback=a?this.mixer.accurate.bind(this.mixer):this.mixer.fast.bind(this.mixer)}},toggle:{set:function(a){this.mixer.channels[a].mute^=1}},core_initialize:{value:function(){this.timer=this.speed;this.tick=0;this.mixer.initialize();this.mixer.samplesTick=2.5*this.sampleRate/this.tempo>>0}},load:{value:function(a){this.mixer.reset();this.version=0;a=createByteArray(a);a.endian=this.endian;this.loader(a);this.version&&this.setup();
return this.version}},play:{value:function(){var a=this.callback,b;if(this.version)this.paused?this.paused=0:(this.initialize(),this.node=this.context.createJavaScriptNode(this.mixer.bufferSize),this.node.onaudioprocess=function(b){a(b)}),this.analyse?(node=neoart.analyserNode=this.context.createAnalyser(),this.node.connect(node),node.connect(this.context.destination)):this.node.connect(this.context.destination),b=document.createEvent("Event"),b.initEvent("flodPlay",!0,!1),document.dispatchEvent(b)}},
pause:{value:function(){if(this.node){this.node.disconnect();this.paused=1;var a=document.createEvent("Event");a.initEvent("flodPause",!0,!1);document.dispatchEvent(a)}}},stop:{value:function(){if(this.node){this.node.disconnect();this.node.onaudioprocess=this.node=null;this.paused=0;var a=document.createEvent("Event");a.initEvent("flodStop",!0,!1);document.dispatchEvent(a)}}},setup:{configurable:!0,value:function(){}}});if(!window.neoart.AudioContext)window.neoart.AudioContext=new webkitAudioContext;
b.context=window.neoart.AudioContext;b.sampleRate=b.context.sampleRate;return b};