/*
  JavaScript Flod 1.0
  2011/11/30
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function h(g){return Object.create(null,{index:{value:g,writable:!0},next:{value:null,writable:!0},sample:{value:null,writable:!0},trackPtr:{value:0,writable:!0},trackPos:{value:0,writable:!0},trackLen:{value:0,writable:!0},patternPos:{value:0,writable:!0},restart:{value:0,writable:!0},step:{value:null,writable:!0},row:{value:null,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},finalPeriod:{value:0,writable:!0},arpeggioPtr:{value:0,writable:!0},arpeggioPos:{value:0,
writable:!0},pitchBend:{value:0,writable:!0},portamento:{value:0,writable:!0},tableCtr:{value:0,writable:!0},tablePos:{value:0,writable:!0},vibratoCtr:{value:0,writable:!0},vibratoDir:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},vibratoPeriod:{value:0,writable:!0},vibratoSustain:{value:0,writable:!0},volume:{value:0,writable:!0},volumeMax:{value:0,writable:!0},volumePos:{value:0,writable:!0},volumeSustain:{value:0,writable:!0},initialize:{value:function(){this.sample=null;this.restart=this.patternPos=
this.trackLen=this.trackPos=this.trackPtr=0;this.row=this.step=null;this.volume=this.vibratoSustain=this.vibratoPeriod=this.vibratoPos=this.vibratoDir=this.vibratoCtr=this.tablePos=this.tableCtr=this.portamento=this.pitchBend=this.arpeggioPos=this.arpeggioPtr=this.finalPeriod=this.period=this.note=0;this.volumeMax=63;this.volumeSustain=this.volumePos=0}}})}window.neoart.createD2Player=function(g){g=createAmigaPlayer(g);Object.defineProperties(g,{id:{value:"D2Player"},tracks:{value:null,writable:!0},
patterns:{value:[],writable:!0},samples:{value:[],writable:!0},data:{value:[],writable:!0},arpeggios:{value:null,writable:!0},voices:{value:[],writable:!0},noise:{value:0,writable:!0},initialize:{value:function(){var c=this.voices[0];this.core_initialize();this.timer=5;this.tick=1;for(this.noise=0;c;)c.initialize(),c.channel=this.mixer.channels[c.index],c.sample=this.samples[this.samples.length-1],c.trackPtr=this.data[c.index],c.restart=this.data[c.index+4],c.trackLen=this.data[c.index+8],c=c.next}},
loader:{value:function(c){var d,b,e=0,a,g,f;c.position=3014;if(".FNL"==c.readString(4)){c.position=4042;this.data=new Int32Array(12);for(d=0;4>d;++d)this.data[d+4]=c.readUnsignedShort(),f=c.readUnsignedShort()>>1,this.data[d+8]=f,e+=f;f=e;for(d=3;0<d;--d)this.data[d]=f-=this.data[d+8];this.tracks=[];this.tracks.length=e;for(d=0;d<e;++d)b=this.createStep(),b.pattern=c.readUnsignedByte()<<4,b.transpose=c.readByte(),this.tracks[d]=b;e=c.readUnsignedInt()>>2;this.patterns=[];this.patterns.length=e;for(d=
0;d<e;++d)b=this.mixer.createRow(),b.note=c.readUnsignedByte(),b.sample=c.readUnsignedByte(),b.effect=c.readUnsignedByte()-1,b.param=c.readUnsignedByte(),this.patterns[d]=b;c.position+=254;f=c.readUnsignedShort();g=c.position;c.position-=256;e=1;a=new Int32Array(128);for(d=0;128>d;++d)b=c.readUnsignedShort(),b!=f&&(a[e++]=b);this.samples=[];this.samples.length=e;for(d=0;d<e;++d){c.position=g+a[d];f=this.createSample();f.length=c.readUnsignedShort()<<1;f.loop=c.readUnsignedShort();f.repeat=c.readUnsignedShort()<<
1;for(b=0;15>b;++b)f.volumes[b]=c.readUnsignedByte();for(b=0;15>b;++b)f.vibratos[b]=c.readUnsignedByte();f.pitchBend=c.readUnsignedShort();f.synth=c.readByte();f.index=c.readUnsignedByte();for(b=0;48>b;++b)f.table[b]=c.readUnsignedByte();this.samples[d]=f}e=c.readUnsignedInt();this.mixer.store(c,e);c.position+=64;for(d=0;8>d;++d)a[d]=c.readUnsignedInt();e=this.samples.length;g=c.position;for(d=0;d<e;++d)if(f=this.samples[d],!(0<=f.synth))c.position=g+a[f.index],f.pointer=this.mixer.store(c,f.length),
f.loopPtr=f.pointer+f.loop;c.position=3018;for(d=0;1024>d;++d)this.arpeggios[d]=c.readByte();f=this.createSample();f.pointer=f.loopPtr=this.mixer.memory.length;f.length=f.repeat=2;this.samples[e]=f;this.version=1}}},process:{value:function(){var c;c=0;for(var d,b,e,a=this.voices[0];64>c;)this.noise=this.noise<<7|this.noise>>>25,this.noise+=1858762093,this.noise^=2656676139,b=this.noise>>>24&255,127<b&&(b|=-256),this.mixer.memory[c++]=b,b=this.noise>>>16&255,127<b&&(b|=-256),this.mixer.memory[c++]=
b,b=this.noise>>>8&255,127<b&&(b|=-256),this.mixer.memory[c++]=b,b=this.noise&255,127<b&&(b|=-256),this.mixer.memory[c++]=b;if(0>--this.tick)this.tick=this.timer;for(;a;){if(!(1>a.trackLen)){c=a.channel;e=a.sample;if(e.synth)c.pointer=e.loopPtr,c.length=e.repeat;if(0==this.tick){if(0==a.patternPos&&(a.step=this.tracks[a.trackPtr+a.trackPos],++a.trackPos==a.trackLen))a.trackPos=a.restart;b=a.row=this.patterns[a.step.pattern+a.patternPos];if(b.note){c.enabled=0;a.note=b.note;a.period=i[b.note+a.step.transpose];
e=a.sample=this.samples[b.sample];if(0>e.synth)c.pointer=e.pointer,c.length=e.length;a.arpeggioPos=0;a.tableCtr=0;a.tablePos=0;a.vibratoCtr=e.vibratos[1];a.vibratoPos=0;a.vibratoDir=0;a.vibratoPeriod=0;a.vibratoSustain=e.vibratos[2];a.volume=0;a.volumePos=0;a.volumeSustain=0}switch(b.effect){case 0:this.timer=b.param&15;break;case 1:this.mixer.filter.active=b.param;break;case 2:a.pitchBend=~(b.param&255)+1;break;case 3:a.pitchBend=b.param&255;break;case 4:a.portamento=b.param;break;case 5:a.volumeMax=
b.param&63;break;case 6:this.mixer.volume=b.param;break;case 7:a.arpeggioPtr=(b.param&63)<<4}a.patternPos=++a.patternPos&15}e=a.sample;if(0<=e.synth)if(a.tableCtr)a.tableCtr--;else{a.tableCtr=e.index;b=e.table[a.tablePos];if(255==b&&(b=e.table[++a.tablePos],255!=b))a.tablePos=b,b=e.table[a.tablePos];if(255!=b&&(c.pointer=b<<8,c.length=e.length,47<++a.tablePos))a.tablePos=0}b=e.vibratos[a.vibratoPos];a.vibratoPeriod=a.vibratoDir?a.vibratoPeriod-b:a.vibratoPeriod+b;if(0==--a.vibratoCtr)a.vibratoCtr=
e.vibratos[a.vibratoPos+1],a.vibratoDir=~a.vibratoDir;if(a.vibratoSustain)a.vibratoSustain--;else{a.vibratoPos+=3;if(15==a.vibratoPos)a.vibratoPos=12;a.vibratoSustain=e.vibratos[a.vibratoPos+2]}if(a.volumeSustain)a.volumeSustain--;else if(b=e.volumes[a.volumePos],d=e.volumes[a.volumePos+1],d<a.volume){if(a.volume-=b,a.volume<d)a.volume=d,a.volumePos+=3,a.volumeSustain=e.volumes[a.volumePos-1]}else if(a.volume+=b,a.volume>d){a.volume=d;a.volumePos+=3;if(15==a.volumePos)a.volumePos=12;a.volumeSustain=
e.volumes[a.volumePos-1]}if(a.portamento)if(a.period<a.finalPeriod){if(a.finalPeriod-=a.portamento,a.finalPeriod<a.period)a.finalPeriod=a.period}else if(a.finalPeriod+=a.portamento,a.finalPeriod>a.period)a.finalPeriod=a.period;b=this.arpeggios[a.arpeggioPtr+a.arpeggioPos];if(-128==b)a.arpeggioPos=0,b=this.arpeggios[a.arpeggioPtr];a.arpeggioPos=++a.arpeggioPos&15;if(0==a.portamento)b=a.note+a.step.transpose+b,0>b&&(b=0),a.finalPeriod=i[b];a.vibratoPeriod-=e.pitchBend-a.pitchBend;c.period=a.finalPeriod+
a.vibratoPeriod;b=a.volume>>2&63;if(b>a.volumeMax)b=a.volumeMax;c.volume=b;c.enabled=1}a=a.next}}},createSample:{value:function(){var c=this.mixer.createSample();Object.defineProperties(c,{index:{value:0,writable:!0},pitchBend:{value:0,writable:!0},synth:{value:0,writable:!0},table:{value:null,writable:!0},vibratos:{value:null,writable:!0},volumes:{value:null,writable:!0}});c.table=new Int32Array(48);c.vibratos=new Int32Array(15);c.volumes=new Int32Array(15);return c}},createStep:{value:function(){return Object.create(null,
{pattern:{value:0,writable:!0},transpose:{value:0,writable:!0}})}}});g.arpeggios=new Int32Array(1024);g.voices[0]=h(0);g.voices[0].next=g.voices[1]=h(1);g.voices[1].next=g.voices[2]=h(2);g.voices[2].next=g.voices[3]=h(3);return Object.seal(g)};var i=[0,6848,6464,6096,5760,5424,5120,4832,4560,4304,4064,3840,3616,3424,3232,3048,2880,2712,2560,2416,2280,2152,2032,1920,1808,1712,1616,1524,1440,1356,1280,1208,1140,1076,1016,960,904,856,808,762,720,678,640,604,570,538,508,480,452,428,404,381,360,339,320,
302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,113,113,113,113,113,113,113,113,113,113,113,113]})();