/*
  JavaScript Flod 1.0
  2011/11/30
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function j(h){return Object.create(null,{index:{value:h,writable:!0},next:{value:null,writable:!0},byte0:{value:0,writable:!0},byte1:{value:0,writable:!0},note:{value:0,writable:!0},byte3:{value:0,writable:!0},stepPtr:{value:0,writable:!0},patternPtr:{value:0,writable:!0},patternPos:{value:0,writable:!0},table2Ptr:{value:0,writable:!0},table2Pos:{value:0,writable:!0},byte20:{value:0,writable:!0},byte21:{value:0,writable:!0},sampleDone:{value:0,writable:!0},sample:{value:null,writable:!0},
speed:{value:0,writable:!0},counter:{value:0,writable:!0},word32:{value:0,writable:!0},long34:{value:0,writable:!0},long38:{value:0,writable:!0},byte42:{value:0,writable:!0},byte43:{value:0,writable:!0},byte44:{value:0,writable:!0},byte45:{value:0,writable:!0},byte46:{value:0,writable:!0},initialize:{value:function(){this.patternPtr=this.stepPtr=this.byte3=this.note=this.byte1=this.byte0=0;this.patternPos=2;this.byte21=this.byte20=this.table2Pos=this.table2Ptr=0;this.sampleDone=-1;this.sample=null;
this.speed=0;this.counter=1;this.byte46=this.byte45=this.byte44=this.byte43=this.byte42=this.long38=this.long34=this.word32=0}}})}window.neoart.createDWPlayer=function(h){h=createAmigaPlayer(h);Object.defineProperties(h,{song:{value:null,writable:!0},songs:{value:[],writable:!0},samples:{value:[],writable:!0},voices:{value:[],writable:!0},stream:{value:null,writable:!0},offset:{value:0,writable:!0},channels:{value:0,writable:!0},master:{value:0,writable:!0},periods:{value:0,writable:!0},table1:{value:0,
writable:!0},table2:{value:0,writable:!0},table3:{value:0,writable:!0},com2:{value:0,writable:!0},com3:{value:0,writable:!0},com4:{value:0,writable:!0},wave:{value:null,writable:!0},waveDir:{value:0,writable:!0},wavePos:{value:0,writable:!0},waveMin:{value:0,writable:!0},waveMax:{value:0,writable:!0},waveStep:{value:0,writable:!0},sample1:{value:0,writable:!0},sample2:{value:0,writable:!0},byte5b6:{value:0,writable:!0},byte5ba:{value:0,writable:!0},masterTimer:{value:0,writable:!0},masterSpeed:{value:0,
writable:!0},interval:{value:0,writable:!0},counter:{value:0,writable:!0},multiply:{value:0,writable:!0},initialize:{value:function(){var a,f,e=this.voices[0];this.core_initialize();this.song=this.songs[this.playSong];this.timer=this.song.speed;this.tick=this.song.timer;this.waveDir=this.byte5ba=this.byte5b6=0;this.wavePos=this.waveMin;this.masterSpeed=this.masterTimer=0;this.counter=6;if(0==this.multiply)this.multiply=1;if(this.wave){a=this.wave.pointer;for(f=a+(this.wave.length>>1);a<f;++a)this.mixer.memory[a]=
this.sample1;a=f;for(f+=this.wave.length>>1;a<f;++a)this.mixer.memory[a]=this.sample2}for(;e;)e.initialize(),e.channel=this.mixer.channels[e.index],e.sample=this.samples[0],e.patternPtr=this.song.pointers[e.index]+this.offset,this.stream.position=e.patternPtr,e.stepPtr=this.stream.readUnsignedShort()+this.offset,e.table2Ptr=this.table2,e.table2Pos=this.table2,e=e.next}},loader:{value:function(a){var f,e,g,d,b,h,i,c;c=a.readUnsignedShort();if(18663==c&&(a.position=4,c=a.readUnsignedShort(),24832==
c)){for(a.position+=a.readUnsignedShort();20085!=c;){c=a.readUnsignedShort();switch(c){case 24832:a.position+=2;c=a.readUnsignedShort();if(24832!=c)return;e=a.position+a.readUnsignedShort();break;case 16890:d=a.position+a.readUnsignedShort();break;case 20713:a.position+=2;c=a.readUnsignedShort();if(16890!=c)return;this.table2=a.position+a.readUnsignedShort();break;case 48764:f=this.channels=a.readUnsignedShort();a.position+=2;c=a.readUnsignedShort();if(14204==c)this.master=a.readUnsignedShort();c=
20085}if(0==a.bytesAvailable)return}this.songs=[];b=2147483647;i=0;for(a.position=d;a.position<b;){h=this.createSong();h.pointers=new Uint16Array(f);h.speed=a.readUnsignedByte();h.timer=a.readUnsignedByte();for(g=0;g<f;++g)c=a.readUnsignedShort(),c<b&&(b=c),h.pointers[g]=c;this.songs[i++]=h}this.lastSong=--i;a.position=e;c=a.readUnsignedShort();if(18987==c){for(;20085!=c;){c=a.readUnsignedShort();if(16890==c){e=a.position+a.readUnsignedShort();c=a.readUnsignedShort();if(19450!=c)for(;19450!=c;)if(c=
a.readUnsignedShort(),53500==c&&(e+=a.readUnsignedShort()),0==a.bytesAvailable)return;d=a.position+a.readShort();a.position++;i=a.readUnsignedByte();this.samples=[];this.samples.length=++i;f=a.position;a.position=e;for(g=0;g<i;++g){b=this.createSample();b.length=a.readUnsignedInt();b.period=a.readUnsignedShort();if(0==b.period)return;b.period=3579545/b.period>>0;b.pointer=c=a.position;a.position=d+12*g+4;b.loopStart=a.readInt();a.position=b.pointer;b.pointer=this.mixer.memory.length;this.mixer.store(a,
b.length);a.position=c+b.length;this.samples[g]=b}this.mixer.loopLen=64;a.length=e;a.position=f}else if(20715==c)for(;20085!=c;)switch(c=a.readUnsignedShort(),c){case 1131:c=a.readUnsignedShort();b=(a.readUnsignedShort()-d)/12>>0;this.samples[b].period-=c;break;case 1643:c=a.readUnsignedShort();b=(a.readUnsignedShort()-d)/12>>0;this.samples[b].period+=c;break;case 8314:c=(a.position+a.readShort()-d)/12>>0,this.wave=this.samples[c],a.position+=6,this.sample1=a.readByte(),a.position+=12,this.sample2=
a.readByte(),a.position+=12,this.wave.length=a.readUnsignedShort()<<1,c=20085}if(0==a.bytesAvailable)return}a.position=330;this.com2=176;this.com3=160;this.com4=144;for(this.waveStep=g=1;g;){c=a.readUnsignedShort();switch(c){case 18426:this.offset=a.position+a.readShort();c=a.readUnsignedShort();if(18987!=c)break;a.position+=4;c=a.readUnsignedShort();if(18987==c)f=a.position,a.position=a.readUnsignedShort(),this.interval=a.readByte(),a.position=f;else if(4154==c&&(a.position+=4,c=a.readUnsignedShort(),
49404==c))this.multiply=a.readUnsignedShort();break;case 12732:this.waveStep=2;case 4540:a.position++;c=a.readByte();if(c==this.sample1){if(a.position+=6,c=a.readUnsignedShort(),3179==c)this.waveMax=a.readUnsignedShort()}else if(c==this.sample2&&(a.position+=6,c=a.readUnsignedShort(),3179==c))this.waveMin=a.readUnsignedShort();break;case 49858:if(0!=this.master)break;f=a.position;a.position-=4;a.position+=a.readUnsignedShort();this.master=a.readUnsignedShort();a.position=f;break;case 15681:c=a.readUnsignedShort();
if(168!=c)break;a.position+=8;c=a.readUnsignedShort();if(12845!=c)break;a.position-=4;this.periods=a.position+a.readUnsignedShort();break;case 45116:if(c=a.readUnsignedShort(),192==c)this.com2=192,this.com3=176,this.com4=160;else if(c==this.com3)a.position+=10,this.table3=a.position+a.readUnsignedShort();else if(c==this.com4)a.position+=10,this.table1=a.position+a.readShort(),g=0}if(0==a.bytesAvailable)return}if(!(0==this.periods||0==this.table1||0==this.table3))this.com2-=256,this.com3-=256,this.com4-=
256,this.version=1,this.stream=a}}}},process:{value:function(){var a,f,e,g,d,b=this.voices[0];if(this.interval&&0==--this.counter)this.counter=6;else if(this.byte5b6+=this.timer*this.multiply,255<this.byte5b6)this.byte5b6&=255;else{if(0!=this.masterTimer&&0!=this.master&&(0==--this.masterSpeed&&this.master--,0!=this.master))this.masterSpeed=this.masterTimer;if(0==this.master)this.mixer.complete=1;else{if(this.wave){e=this.wave.pointer+this.wavePos;if(0>this.waveDir){if(a=this.sample2,this.wavePos-=
2,this.wavePos==this.waveMin)this.waveDir=0}else if(a=this.sample1,this.wavePos+=2,this.wavePos==this.waveMax)this.waveDir=-1;this.mixer.memory[e++]=a;2==this.waveStep&&(this.mixer.memory[e]=a)}for(;b;){a=b.channel;this.stream.position=b.stepPtr;g=b.sample;if(0==b.sampleDone)b.sampleDone=-1,0>g.loopStart?(a.pointer=this.mixer.loopPtr,a.length=64):(a.pointer=g.pointer+g.loopStart,a.length=g.length-g.loopStart);if(0==--b.counter){b.byte0=0;for(f=1;0<f;)if(d=this.stream.readByte(),0>d)if(-32<=d)d+=33,
b.speed=this.timer*d;else if(d>=this.com2)d-=this.com2,b.sample=g=this.samples[d];else if(d>=this.com3)d-=this.com3,e=this.stream.position,this.stream.position=this.table3+(d<<1),this.stream.position=this.stream.readUnsignedShort()+this.offset,b.long34=this.stream.position,this.stream.position--,b.byte42=this.stream.readByte(),this.stream.position=e;else if(d>=this.com4)d-=this.com4,e=this.stream.position,this.stream.position=this.table1+(d<<1),b.table2Ptr=this.stream.readUnsignedShort()+this.offset,
b.table2Pos=b.table2Ptr,this.stream.position=e;else switch(d+=128,d){case 0:this.stream.position=b.patternPtr+b.patternPos;(d=this.stream.readUnsignedShort())?(this.stream.position=d+this.offset,b.patternPos+=2):(this.stream.position=b.patternPtr,this.stream.position=this.stream.readUnsignedShort()+this.offset,b.patternPos=2);break;case 1:b.word32=0;b.byte20=this.stream.readByte();b.byte21=this.stream.readByte();b.byte0|=2;break;case 2:b.counter=b.speed;b.stepPtr=this.stream.position;a.pointer=this.mixer.loopPtr;
a.length=64;f=-1;break;case 3:f=-2;break;case 4:this.mixer.complete=1;f=-1;break;case 5:this.byte5ba=this.stream.readByte();break;case 6:b.byte1=-1;b.byte44=this.stream.readByte();b.byte46=this.stream.readByte();b.byte45=0;break;case 7:b.byte1=0;break;case 8:b.byte3=this.stream.readByte();break;case 9:b.patternPtr=this.stream.readUnsignedShort()+this.offset;b.patternPos=0;break;case 10:this.timer=this.stream.readByte();break;case 11:this.masterSpeed=this.masterTimer=this.stream.readByte();break;case 12:this.master=
this.stream.readByte();break;}else break;if(-1==f)continue;b.stepPtr=this.stream.position;b.counter=b.speed;if(-2!=f)b.note=d,d+=this.byte5ba+b.byte3,this.stream.position=b.long34,e=this.stream.readByte()*this.master>>6,b.long38=this.stream.position,b.byte43=b.byte42,a.pointer=g.pointer,a.length=g.length,a.volume=e,this.stream.position=this.periods+(d<<1),a.period=this.stream.readUnsignedShort()*g.period>>10,b.sampleDone=0;a.enabled=1}else if(1==b.counter){if(131!=
b.byte0)a.enabled=0;continue}else{this.stream.position=b.table2Pos;d=this.stream.readByte();0>d?(d+=128,b.table2Pos=b.table2Ptr):b.table2Pos++;d+=b.note+b.byte3+this.byte5ba;this.stream.position=this.periods+(d<<1);d=this.stream.readUnsignedShort()*g.period>>10;0!=(b.byte0&2)&&(b.byte21?b.byte21--:(b.word32+=b.byte20,d-=b.word32));if(b.byte1){if(0>b.byte1)b.byte45+=b.byte44,b.byte46==b.byte45&&(b.byte1+=128);else if(b.byte45-=b.byte44,0==b.byte45)b.byte1=-1;if(0==b.byte45)b.byte1=-2;d=0==(b.byte1&
1)?d-b.byte45:d+b.byte45}a.period=d;if(0>--b.byte43)b.byte43=b.byte42,this.stream.position=b.long38,e=this.stream.readByte(),-1<e&&b.long38++,a.volume=(e&127)*this.master>>6}b=b.next}}}}},createSample:{value:function(){return Object.create(null,{length:{value:0,writable:!0},loopStart:{value:0,writable:!0},period:{value:0,writable:!0},volume:{value:0,writable:!0},pointer:{value:0,writable:!0}})}},createSong:{value:function(){return Object.create(null,{pointers:{value:null,writable:!0},speed:{value:0,
writable:!0},timer:{value:0,writable:!0}})}}});h.voices[0]=j(0);h.voices[0].next=h.voices[1]=j(1);h.voices[1].next=h.voices[2]=j(2);h.voices[2].next=h.voices[3]=j(3);return Object.seal(h)}})();