/*
  JavaScript Flod 1.0
  2011/11/30
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function j(g){return Object.create(null,{index:{value:g,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},enabled:{value:0,writable:!0},period:{value:0,writable:!0},effect:{value:0,writable:!0},param:{value:0,writable:!0},volume:{value:0,writable:!0},last:{value:0,writable:!0},slideCtr:{value:0,writable:!0},slideDir:{value:0,writable:!0},slideParam:{value:0,writable:!0},slidePeriod:{value:0,writable:!0},slideSpeed:{value:0,writable:!0},
stepPeriod:{value:0,writable:!0},stepSpeed:{value:0,writable:!0},stepWanted:{value:0,writable:!0},initialize:{value:function(){this.sample=this.channel=null;this.stepWanted=this.stepSpeed=this.stepPeriod=this.slideSpeed=this.slidePeriod=this.slideParam=this.slideDir=this.slideCtr=this.last=this.volume=this.param=this.effect=this.period=this.enabled=0}}})}window.neoart.createFXPlayer=function(g){g=createAmigaPlayer(g);Object.defineProperties(g,{id:{value:"FXPlayer"},track:{value:null,writable:!0},
patterns:{value:[],writable:!0},samples:{value:[],writable:!0},length:{value:0,writable:!0},voices:{value:[],writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},jumpFlag:{value:0,writable:!0},force:{set:function(b){b<m?b=m:b>k&&(b=k);this.version=b}},ntsc:{set:function(b){this.mode(b);b=(b?20.44952532:20.637767904)*(this.sampleRate/1E3)/120;this.mixer.samplesTick=this.tempo/122*b>>0}},initialize:{value:function(){var b=this.voices[0];this.core_initialize();this.ntsc=this.standard;
this.timer=6;for(this.jumpFlag=this.patternPos=this.trackPos=0;b;)b.initialize(),b.channel=this.mixer.channels[b.index],b.sample=this.samples[0],b=b.next}},loader:{value:function(b){var c=0,e,d,a,f,g=0,h;if(!(1686>b.length)){b.position=60;e=b.readString(4);if("SONG"!=e){b.position=124;e=b.readString(4);if("SO31"!=e)return;if(2350>b.length)return;d=32;a=544;this.version=k}else d=16,a=0,this.version=m;this.tempo=b.readUnsignedShort();b.position=0;for(e=1;e<d;++e)(h=b.readUnsignedInt())?(f=this.mixer.createSample(),
f.pointer=g,g+=h,this.samples[e]=f):this.samples[e]=null;b.position+=20;for(e=1;e<d;++e)(f=this.samples[e])?(f.name=b.readString(22),f.length=b.readUnsignedShort()<<1,f.volume=b.readUnsignedShort(),f.loop=b.readUnsignedShort(),f.repeat=b.readUnsignedShort()<<1):b.position+=30;b.position=530+a;this.length=d=b.readUnsignedByte();b.position++;for(e=0;e<d;++e)h=b.readUnsignedByte()<<8,this.track[e]=h,h>c&&(c=h);a&&(a+=4);b.position=660+a;c+=256;this.patterns=[];this.patterns.length=c;d=this.samples.length;
for(e=0;e<c;++e){a=this.mixer.createRow();a.note=b.readShort();h=b.readUnsignedByte();a.param=b.readUnsignedByte();a.effect=h&15;a.sample=h>>4;this.patterns[e]=a;if(this.version==k)a.note&4096&&(a.sample+=16,0<a.note&&(a.note&=61439));else{if(9==a.effect||856<a.note)this.version=i;if(-3>a.note)this.version=n}if(a.sample>=d||null==this.samples[a.sample])a.sample=0}this.mixer.store(b,g);for(e=1;e<d;++e)if(f=this.samples[e]){f.loop?f.loopPtr=f.pointer+f.loop:(f.loopPtr=this.mixer.memory.length,f.repeat=
2);g=f.pointer+4;for(b=f.pointer;b<g;++b)this.mixer.memory[b]=0}f=this.mixer.createSample();f.pointer=f.loopPtr=this.mixer.memory.length;f.length=f.repeat=2;this.samples[0]=f}}},process:{value:function(){var f;var b,c,e,d,a=this.voices[0];if(this.tick)for(;a;){b=a.channel;if(!(this.version==i&&-3==a.period))if(a.stepSpeed){a.stepPeriod+=a.stepSpeed;if(0>a.stepSpeed){if(a.stepPeriod<a.stepWanted&&(a.stepPeriod=a.stepWanted,this.version>i))a.stepSpeed=0}else if(a.stepPeriod>a.stepWanted&&(a.stepPeriod=
a.stepWanted,this.version>i))a.stepSpeed=0;if(this.version>i)a.last=a.stepPeriod;b.period=a.stepPeriod}else{if(a.slideSpeed&&(d=a.slideParam&15))if(++a.slideCtr==d)if(a.slideCtr=0,d=a.slideParam>>4<<3,0==a.slideDir){if(a.slidePeriod+=8,b.period=a.slidePeriod,d+=a.slideSpeed,d==a.slidePeriod)a.slideDir=1}else{if(a.slidePeriod-=8,b.period=a.slidePeriod,d-=a.slideSpeed,d==a.slidePeriod)a.slideDir=0}else{a=a.next;continue}d=0;switch(a.effect){case 1:d=o[this.tick-1];c=0;if(2==d){b.period=a.last;a=a.next;
continue}for(d=1==d?a.param&15:a.param>>4;a.last!=l[c];)c++;b.period=l[c+d];break;case 2:d=a.param>>4;a.period=d?a.period+d:a.period-(a.param&15);b.period=a.period;break;case 3:this.mixer.filter.active=1;break;case 4:this.mixer.filter.active=0;break;case 8:d=-1;case 7:a.stepSpeed=a.param&15;e=this.version>i?a.last:a.period;if(0>d)a.stepSpeed=-a.stepSpeed;for(c=0;;){b=l[c];if(b==e)break;if(0>b){c=-1;break}else c++}-1<c?(b=a.param>>4,-1<d&&(b=-b),c+=b,0>c&&(c=0),a.stepWanted=l[c]):a.stepWanted=a.period;
break;case 9:a.slideSpeed=a.slidePeriod=a.period,a.slideParam=a.param,a.slideDir=0,a.slideCtr=0}}a=a.next}else for(d=this.track[this.trackPos]+this.patternPos;a;){b=a.channel;a.enabled=0;c=this.patterns[d+a.index];a.period=c.note;a.effect=c.effect;a.param=c.param;if(-3==c.note)a.effect=0;else if(c.sample?(f=a.sample=this.samples[c.sample],c=f,a.volume=c.volume,5==a.effect?a.volume+=a.param:6==a.effect&&(a.volume-=a.param),b.volume=a.volume):c=a.sample,a.period){a.last=a.period;a.slideSpeed=0;a.stepSpeed=
0;a.enabled=1;b.enabled=0;switch(a.period){case -2:b.volume=0;break;case -4:this.jumpFlag=1;break;default:b.pointer=c.pointer,b.length=c.length,b.period=a.period}if(a.enabled)b.enabled=1;b.pointer=c.loopPtr;b.length=c.repeat}a=a.next}if(++this.tick==this.timer&&(this.tick=0,this.patternPos+=4,256==this.patternPos||this.jumpFlag))if(this.patternPos=this.jumpFlag=0,++this.trackPos==this.length)this.trackPos=0,this.mixer.complete=1}}});g.track=new Uint32Array(128);
g.voices[0]=j(0);g.voices[0].next=g.voices[1]=j(1);g.voices[1].next=g.voices[2]=j(2);g.voices[2].next=g.voices[3]=j(3);return Object.seal(g)};var m=1,i=2,n=3,k=4,o=[0,1,2,1,0],l=[1076,1016,960,906,856,808,762,720,678,640,604,570,538,508,480,453,428,404,381,360,339,320,302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,-1]})();