/*
  JavaScript Flod 1.0
  2012/02/08
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function h(g){return Object.create(null,{index:{value:g,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},trackPtr:{value:0,writable:!0},trackPos:{value:0,writable:!0},trackLen:{value:0,writable:!0},patternPos:{value:0,writable:!0},restart:{value:0,writable:!0},step:{value:null,writable:!0},row:{value:null,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},finalPeriod:{value:0,writable:!0},arpeggioPtr:{value:0,
writable:!0},arpeggioPos:{value:0,writable:!0},pitchBend:{value:0,writable:!0},portamento:{value:0,writable:!0},tableCtr:{value:0,writable:!0},tablePos:{value:0,writable:!0},vibratoCtr:{value:0,writable:!0},vibratoDir:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},vibratoPeriod:{value:0,writable:!0},vibratoSustain:{value:0,writable:!0},volume:{value:0,writable:!0},volumeMax:{value:0,writable:!0},volumePos:{value:0,writable:!0},volumeSustain:{value:0,writable:!0},initialize:{value:function(){this.sample=
null;this.restart=this.patternPos=this.trackLen=this.trackPos=this.trackPtr=0;this.row=this.step=null;this.volume=this.vibratoSustain=this.vibratoPeriod=this.vibratoPos=this.vibratoDir=this.vibratoCtr=this.tablePos=this.tableCtr=this.portamento=this.pitchBend=this.arpeggioPos=this.arpeggioPtr=this.finalPeriod=this.period=this.note=0;this.volumeMax=63;this.volumeSustain=this.volumePos=0}}})}function i(){var g=AmigaSample();Object.defineProperties(g,{index:{value:0,writable:!0},pitchBend:{value:0,writable:!0},
synth:{value:0,writable:!0},table:{value:null,writable:!0},vibratos:{value:null,writable:!0},volumes:{value:null,writable:!0}});g.table=new Uint8Array(48);g.vibratos=new Uint8Array(15);g.volumes=new Uint8Array(15);return Object.seal(g)}var j=[0,6848,6464,6096,5760,5424,5120,4832,4560,4304,4064,3840,3616,3424,3232,3048,2880,2712,2560,2416,2280,2152,2032,1920,1808,1712,1616,1524,1440,1356,1280,1208,1140,1076,1016,960,904,856,808,762,720,678,640,604,570,538,508,480,452,428,404,381,360,339,320,302,285,
269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,113,113,113,113,113,113,113,113,113,113,113,113];window.neoart.D2Player=function(g){g=AmigaPlayer(g);Object.defineProperties(g,{id:{value:"D2Player"},tracks:{value:[],writable:!0},patterns:{value:[],writable:!0},samples:{value:[],writable:!0},data:{value:null,writable:!0},arpeggios:{value:null,writable:!0},voices:{value:[],writable:!0},noise:{value:0,writable:!0},initialize:{value:function(){var c=this.voices[0];this.reset();this.speed=
5;this.tick=1;for(this.noise=0;c;)c.initialize(),c.channel=this.mixer.channels[c.index],c.sample=this.samples[this.samples.length-1],c.trackPtr=this.data[c.index],c.restart=this.data[c.index+4],c.trackLen=this.data[c.index+8],c=c.next}},loader:{value:function(c){var d=0,b,e=0,a,g,f;c.position=3014;if(".FNL"==c.readString(4)){c.position=4042;for(this.data=new Uint16Array(12);4>d;++d)this.data[d+4]=c.readUshort(),f=c.readUshort()>>1,this.data[d+8]=f,e+=f;f=e;for(d=3;0<d;--d)this.data[d]=f-=this.data[d+
8];this.tracks.length=e;for(d=0;d<e;++d)b=AmigaStep(),b.pattern=c.readUbyte()<<4,b.transpose=c.readByte(),this.tracks[d]=b;e=c.readUint()>>2;this.patterns.length=e;for(d=0;d<e;++d)b=AmigaRow(),b.note=c.readUbyte(),b.sample=c.readUbyte(),b.effect=c.readUbyte()-1,b.param=c.readUbyte(),this.patterns[d]=b;c.position+=254;f=c.readUshort();g=c.position;c.position-=256;e=1;a=new Uint16Array(128);for(d=0;128>d;++d)b=c.readUshort(),b!=f&&(a[e++]=b);this.samples.length=e;for(d=0;d<e;++d){c.position=g+a[d];
f=i();f.length=c.readUshort()<<1;f.loop=c.readUshort();f.repeat=c.readUshort()<<1;for(b=0;15>b;++b)f.volumes[b]=c.readUbyte();for(b=0;15>b;++b)f.vibratos[b]=c.readUbyte();f.pitchBend=c.readUshort();f.synth=c.readByte();f.index=c.readUbyte();for(b=0;48>b;++b)f.table[b]=c.readUbyte();this.samples[d]=f}e=c.readUint();this.mixer.store(c,e);c.position+=64;for(d=0;8>d;++d)a[d]=c.readUint();e=this.samples.length;g=c.position;for(d=0;d<e;++d)f=this.samples[d],0<=f.synth||(c.position=g+a[f.index],f.pointer=
this.mixer.store(c,f.length),f.loopPtr=f.pointer+f.loop);c.position=3018;for(d=0;1024>d;++d)this.arpeggios[d]=c.readByte();f=i();f.pointer=f.loopPtr=this.mixer.memory.length;f.length=f.repeat=2;this.samples[e]=f;this.version=2}}},process:{value:function(){var c;c=0;for(var d,b,e,a=this.voices[0];64>c;)this.noise=this.noise<<7|this.noise>>>25,this.noise+=1858762093,this.noise^=2656676139,b=this.noise>>>24&255,127<b&&(b|=-256),this.mixer.memory[c++]=b,b=this.noise>>>16&255,127<b&&(b|=-256),this.mixer.memory[c++]=
b,b=this.noise>>>8&255,127<b&&(b|=-256),this.mixer.memory[c++]=b,b=this.noise&255,127<b&&(b|=-256),this.mixer.memory[c++]=b;0>--this.tick&&(this.tick=this.speed);for(;a;){if(!(1>a.trackLen)){c=a.channel;e=a.sample;e.synth&&(c.pointer=e.loopPtr,c.length=e.repeat);if(0==this.tick){0==a.patternPos&&(a.step=this.tracks[a.trackPtr+a.trackPos],++a.trackPos==a.trackLen&&(a.trackPos=a.restart));b=a.row=this.patterns[a.step.pattern+a.patternPos];b.note&&(c.enabled=0,a.note=b.note,a.period=j[b.note+a.step.transpose],
e=a.sample=this.samples[b.sample],0>e.synth&&(c.pointer=e.pointer,c.length=e.length),a.arpeggioPos=0,a.tableCtr=0,a.tablePos=0,a.vibratoCtr=e.vibratos[1],a.vibratoPos=0,a.vibratoDir=0,a.vibratoPeriod=0,a.vibratoSustain=e.vibratos[2],a.volume=0,a.volumePos=0,a.volumeSustain=0);switch(b.effect){case 0:this.speed=b.param&15;break;case 1:this.mixer.filter.active=b.param;break;case 2:a.pitchBend=~(b.param&255)+1;break;case 3:a.pitchBend=b.param&255;break;case 4:a.portamento=b.param;break;case 5:a.volumeMax=
b.param&63;break;case 6:this.mixer.volume=b.param;break;case 7:a.arpeggioPtr=(b.param&63)<<4}a.patternPos=++a.patternPos&15}e=a.sample;0<=e.synth&&(a.tableCtr?a.tableCtr--:(a.tableCtr=e.index,b=e.table[a.tablePos],255==b&&(b=e.table[++a.tablePos],255!=b&&(a.tablePos=b,b=e.table[a.tablePos])),255!=b&&(c.pointer=b<<8,c.length=e.length,47<++a.tablePos&&(a.tablePos=0))));b=e.vibratos[a.vibratoPos];a.vibratoPeriod=a.vibratoDir?a.vibratoPeriod-b:a.vibratoPeriod+b;0==--a.vibratoCtr&&(a.vibratoCtr=e.vibratos[a.vibratoPos+
1],a.vibratoDir=~a.vibratoDir);a.vibratoSustain?a.vibratoSustain--:(a.vibratoPos+=3,15==a.vibratoPos&&(a.vibratoPos=12),a.vibratoSustain=e.vibratos[a.vibratoPos+2]);a.volumeSustain?a.volumeSustain--:(b=e.volumes[a.volumePos],d=e.volumes[a.volumePos+1],d<a.volume?(a.volume-=b,a.volume<d&&(a.volume=d,a.volumePos+=3,a.volumeSustain=e.volumes[a.volumePos-1])):(a.volume+=b,a.volume>d&&(a.volume=d,a.volumePos+=3,15==a.volumePos&&(a.volumePos=12),a.volumeSustain=e.volumes[a.volumePos-1])));a.portamento&&
(a.period<a.finalPeriod?(a.finalPeriod-=a.portamento,a.finalPeriod<a.period&&(a.finalPeriod=a.period)):(a.finalPeriod+=a.portamento,a.finalPeriod>a.period&&(a.finalPeriod=a.period)));b=this.arpeggios[a.arpeggioPtr+a.arpeggioPos];-128==b&&(a.arpeggioPos=0,b=this.arpeggios[a.arpeggioPtr]);a.arpeggioPos=++a.arpeggioPos&15;0==a.portamento&&(b=a.note+a.step.transpose+b,0>b&&(b=0),a.finalPeriod=j[b]);a.vibratoPeriod-=e.pitchBend-a.pitchBend;c.period=a.finalPeriod+a.vibratoPeriod;b=a.volume>>2&63;b>a.volumeMax&&
(b=a.volumeMax);c.volume=b;c.enabled=1}a=a.next}}}});g.voices[0]=h(0);g.voices[0].next=g.voices[1]=h(1);g.voices[1].next=g.voices[2]=h(2);g.voices[2].next=g.voices[3]=h(3);g.arpeggios=new Int8Array(1024);return Object.seal(g)}})();