/*
  Flod JS 2.1
  2012/04/30
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.1 - 2012/04/09

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
function AmigaChannel(c){var b=Object.create(null,{next:{value:null,writable:!0},mute:{value:0,writable:!0},panning:{value:0,writable:!0},delay:{value:0,writable:!0},pointer:{value:0,writable:!0},length:{value:0,writable:!0},audena:{value:0,writable:!0},audcnt:{value:0,writable:!0},audloc:{value:0,writable:!0},audper:{value:0,writable:!0},audvol:{value:0,writable:!0},timer:{value:0,writable:!0},level:{value:0,writable:!0},ldata:{value:0,writable:!0},rdata:{value:0,writable:!0},enabled:{get:function(){return this.audena},
set:function(a){a!=this.audena&&(this.audena=a,this.audloc=this.pointer,this.audcnt=this.pointer+this.length,this.timer=1,a&&(this.delay+=2))}},period:{set:function(a){0>a?a=0:65535<a&&(a=65535);this.audper=a}},volume:{set:function(a){0>a?a=0:64<a&&(a=64);this.audvol=a}},resetData:{value:function(){this.rdata=this.ldata=0}},initialize:{value:function(){this.audloc=this.audcnt=this.audena=0;this.audper=50;this.length=this.pointer=this.delay=this.rdata=this.ldata=this.timer=this.audvol=0}}});b.panning=
b.level=0==(++c&2)?-1:1;return Object.seal(b)}function AmigaFilter(){return Object.create(null,{active:{value:0,writable:!0},forced:{value:-1,writable:!0},l0:{value:0,writable:!0},l1:{value:0,writable:!0},l2:{value:0,writable:!0},l3:{value:0,writable:!0},l4:{value:0,writable:!0},r0:{value:0,writable:!0},r1:{value:0,writable:!0},r2:{value:0,writable:!0},r3:{value:0,writable:!0},r4:{value:0,writable:!0},initialize:{value:function(){this.r0=this.r1=this.r2=this.r3=this.r4=this.l0=this.l1=this.l2=this.l3=this.l4=0}},process:{value:function(c,b){var a=
0.5139651662784244;0==c&&(this.l0=0.4860348337215757*b.l+a*this.l0,this.r0=0.4860348337215757*b.r+a*this.r0,a=0.06850445132502514,b.l=this.l1=0.9314955486749749*this.l0+a*this.l1,b.r=this.r1=0.9314955486749749*this.r0+a*this.r1);0<(this.active|this.forced)&&(a=0.47866541564678,this.l2=0.52133458435322*b.l+a*this.l2,this.r2=0.52133458435322*b.r+a*this.r2,this.l3=0.52133458435322*this.l2+a*this.l3,this.r3=0.52133458435322*this.r2+a*this.r3,b.l=this.l4=0.52133458435322*this.l3+a*this.l4,b.r=this.r4=
0.52133458435322*this.r3+a*this.r4);1<b.l?b.l=1:-1>b.l&&(b.l=-1);1<b.r?b.r=1:-1>b.r&&(b.r=-1)}}})}function AmigaRow(){return Object.create(null,{note:{value:0,writable:!0},sample:{value:0,writable:!0},effect:{value:0,writable:!0},param:{value:0,writable:!0}})}
function AmigaSample(){return Object.create(null,{name:{value:"",writable:!0},length:{value:0,writable:!0},loop:{value:0,writable:!0},repeat:{value:0,writable:!0},volume:{value:0,writable:!0},pointer:{value:0,writable:!0},loopPtr:{value:0,writable:!0}})}function AmigaStep(){return Object.create(null,{pattern:{value:0,writable:!0},transpose:{value:0,writable:!0}})}
function Amiga(){var c=CoreMixer();Object.defineProperties(c,{filter:{value:null,writable:!0},model:{value:1,writable:!0},memory:{value:[],writable:!0},loopPtr:{value:0,writable:!0},loopLen:{value:4,writable:!0},clock:{value:0,writable:!0},master:{value:0,writable:!0},ready:{value:0,writable:!0},volume:{set:function(b){0<b?(64<b&&(b=64),this.master=0.00390625*(b/64)):this.master=0}},initialize:{value:function(){var b=this.memory.length,a=b+this.loopLen;this.reset();this.filter.initialize();if(!this.ready){this.ready=
1;for(this.loopPtr=b;b<a;++b)this.memory[b]=0}}},restore:{value:function(){this.ready=0;this.memory.length=0}},store:{value:function(b,a,l){var c,e,g=b.position,h=this.memory.length;l&&(b.position=l);e=b.position+a;e>=b.length&&(c=e-b.length,a=b.length-b.position);e=h;for(a+=h;e<a;++e)this.memory[e]=b.readByte();for(a+=c;e<a;++e)this.memory[e]=0;l&&(b.position=g);return h}},fast:{value:function(b){var a,c,m=this.memory,e,g=0,h,k=0,n,d,f=this.bufferSize,o,j,i;if(this.completed){if(!this.remains){this.player.stop();
return}f=this.remains}for(;g<f;){this.samplesLeft||(this.player.process(),this.samplesLeft=this.samplesTick,this.completed&&(f=g+this.samplesTick,f>this.bufferSize&&(this.remains=f-this.bufferSize,f=this.bufferSize)));j=this.samplesLeft;g+j>=f&&(j=f-g);h=k+j;for(a=this.channels[0];a;){d=this.buffer[k];if(a.audena&&60<a.audper){o=a.audper/this.clock;i=a.audvol*this.master;e=i*(1-a.level);n=i*(1+a.level);for(c=k;c<h;++c){if(a.delay)a.delay--;else if(1>--a.timer&&(a.mute||(i=0.0078125*m[a.audloc],a.ldata=
i*e,a.rdata=i*n),a.audloc++,a.timer+=o,a.audloc>=a.audcnt))a.audloc=a.pointer,a.audcnt=a.pointer+a.length;d.l+=a.ldata;d.r+=a.rdata;d=d.next}}else for(c=k;c<h;++c)d.l+=a.ldata,d.r+=a.rdata,d=d.next;a=a.next}k=h;g+=j;this.samplesLeft-=j}i=this.model;m=this.filter;d=this.buffer[0];a=b.outputBuffer.getChannelData(0);b=b.outputBuffer.getChannelData(1);for(c=0;c<f;++c)m.process(i,d),a[c]=d.l,b[c]=d.r,d.l=d.r=0,d=d.next}}});c.channels[0]=AmigaChannel(0);c.channels[0].next=c.channels[1]=AmigaChannel(1);
c.channels[1].next=c.channels[2]=AmigaChannel(2);c.channels[2].next=c.channels[3]=AmigaChannel(3);c.bufferSize=8192;c.filter=AmigaFilter();c.master=0.00390625;return Object.seal(c)}function AmigaPlayer(c){var b=CorePlayer();Object.defineProperties(b,{quality:{set:function(){this.callback=this.mixer.fast.bind(this.mixer)}},stereo:{set:function(a){var b=this.mixer.channels[0];for(0>a?a=0:1<a&&(a=1);b;)b.level=a*b.panning,b=b.next}},volume:{set:function(a){0>a?a=0:1<a&&(a=1);this.mixer.master=0.00390625*a}},frequency:{value:function(a){a?(this.mixer.clock=3579545/this.sampleRate,this.mixer.samplesTick=735):(this.mixer.clock=3546895/this.sampleRate,this.mixer.samplesTick=882)}}});
b.mixer=c||Amiga();b.mixer.player=b;b.frequency(0);b.channels=4;b.endian=0;b.quality=0;b.speed=6;b.tempo=125;return b};