/*
  Flod JS 2.1
  2012/04/30
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.0 - 2012/03/30

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function h(f){return Object.create(null,{index:{value:f,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},status:{value:0,writable:!0},speed:{value:0,writable:!0},step:{value:null,writable:!0},row:{value:null,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},arpeggioPos:{value:0,writable:!0},pitchBend:{value:0,writable:!0},tableCtr:{value:0,writable:!0},
tablePos:{value:0,writable:!0},vibratoCtr:{value:0,writable:!0},vibratoDir:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},vibratoPeriod:{value:0,writable:!0},volume:{value:0,writable:!0},attackCtr:{value:0,writable:!0},decayCtr:{value:0,writable:!0},releaseCtr:{value:0,writable:!0},sustain:{value:0,writable:!0},initialize:{value:function(){this.sample=null;this.status=this.patternPos=this.trackPos=0;this.speed=1;this.row=this.step=null;this.releaseCtr=this.decayCtr=this.attackCtr=this.volume=
this.vibratoPeriod=this.vibratoPos=this.vibratoDir=this.vibratoCtr=this.tablePos=this.tableCtr=this.pitchBend=this.arpeggioPos=this.period=this.note=0;this.sustain=1}}})}function i(){var f=AmigaSample();Object.defineProperties(f,{synth:{value:0,writable:!0},attackStep:{value:0,writable:!0},attackDelay:{value:0,writable:!0},decayStep:{value:0,writable:!0},decayDelay:{value:0,writable:!0},releaseStep:{value:0,writable:!0},releaseDelay:{value:0,writable:!0},sustain:{value:0,writable:!0},arpeggio:{value:null,
writable:!0},pitchBend:{value:0,writable:!0},portamento:{value:0,writable:!0},table:{value:null,writable:!0},tableDelay:{value:0,writable:!0},vibratoWait:{value:0,writable:!0},vibratoStep:{value:0,writable:!0},vibratoLen:{value:0,writable:!0}});f.arpeggio=new Int8Array(8);f.table=new Int8Array(48);return Object.seal(f)}var j=[0,6848,6464,6096,5760,5424,5120,4832,4560,4304,4064,3840,3616,3424,3232,3048,2880,2712,2560,2416,2280,2152,2032,1920,1808,1712,1616,1524,1440,1356,1280,1208,1140,1076,960,904,
856,808,762,720,678,640,604,570,538,508,480,452,428,404,381,360,339,320,302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,113,113,113,113,113,113,113,113,113,113,113,113];window.neoart.D1Player=function(f){f=AmigaPlayer(f);Object.defineProperties(f,{id:{value:"D1Player"},pointers:{value:null,writable:!0},tracks:{value:[],writable:!0},patterns:{value:[],writable:!0},samples:{value:[],writable:!0},voices:{value:[],writable:!0},initialize:{value:function(){var d=this.voices[0];
this.reset();for(this.speed=6;d;)d.initialize(),d.channel=this.mixer.channels[d.index],d.sample=this.samples[20],d=d.next}},loader:{value:function(d){var g,b=0,c,a=0,f,e,h;if("ALL "==d.readString(4)){for(g=new Uint32Array(25);25>b;++b)g[b]=d.readUint();this.pointers=new Uint32Array(4);for(b=1;4>b;++b)this.pointers[b]=this.pointers[a]+(g[a++]>>1)-1;f=this.pointers[3]+(g[3]>>1)-1;this.tracks.length=f;c=104+g[1]-2;d.position=104;a=1;for(b=0;b<f;++b)e=AmigaStep(),h=d.readUshort(),65535==h||d.position==
c?(e.pattern=-1,e.transpose=d.readUshort(),c+=g[a++]):(d.position--,e.pattern=(h>>2&16320)>>2,e.transpose=d.readByte()),this.tracks[b]=e;f=g[4]>>2;this.patterns.length=f;for(b=0;b<f;++b)c=AmigaRow(),c.sample=d.readUbyte(),c.note=d.readUbyte(),c.effect=d.readUbyte()&31,c.param=d.readUbyte(),this.patterns[b]=c;c=5;for(b=0;20>b;++b){this.samples[b]=null;if(0!=g[c]){e=i();e.attackStep=d.readUbyte();e.attackDelay=d.readUbyte();e.decayStep=d.readUbyte();e.decayDelay=d.readUbyte();e.sustain=d.readUshort();
e.releaseStep=d.readUbyte();e.releaseDelay=d.readUbyte();e.volume=d.readUbyte();e.vibratoWait=d.readUbyte();e.vibratoStep=d.readUbyte();e.vibratoLen=d.readUbyte();e.pitchBend=d.readByte();e.portamento=d.readUbyte();e.synth=d.readUbyte();e.tableDelay=d.readUbyte();for(a=0;8>a;++a)e.arpeggio[a]=d.readByte();e.length=d.readUshort();e.loop=d.readUshort();e.repeat=d.readUshort()<<1;e.synth=e.synth?0:1;if(e.synth){for(a=0;48>a;++a)e.table[a]=d.readByte();f=g[c]-78}else f=e.length;e.pointer=this.mixer.store(d,
f);e.loopPtr=e.pointer+e.loop;this.samples[b]=e}c++}e=i();e.pointer=e.loopPtr=this.mixer.memory.length;e.length=e.repeat=2;this.samples[20]=e;this.version=1}}},process:{value:function(){for(var d,f,b,c,a=this.voices[0];a;){f=a.channel;if(0==--a.speed&&(a.speed=this.speed,0==a.patternPos&&(a.step=this.tracks[this.pointers[a.index]+a.trackPos],0>a.step.pattern&&(a.trackPos=a.step.transpose,a.step=this.tracks[this.pointers[a.index]+a.trackPos]),a.trackPos++),b=this.patterns[a.step.pattern+a.patternPos],
b.effect&&(a.row=b),b.note&&(f.enabled=0,a.row=b,a.note=b.note+a.step.transpose,a.arpeggioPos=a.pitchBend=a.status=0,c=a.sample=this.samples[b.sample],c.synth||(f.pointer=c.pointer),f.length=c.length,a.tableCtr=a.tablePos=0,a.vibratoCtr=c.vibratoWait,a.vibratoPos=c.vibratoLen,a.vibratoDir=c.vibratoLen<<1,a.volume=a.attackCtr=a.decayCtr=a.releaseCtr=0,a.sustain=c.sustain),16==++a.patternPos))a.patternPos=0;c=a.sample;if(c.synth)if(0==a.tableCtr){a.tableCtr=c.tableDelay;do(d=1,48<=a.tablePos&&(a.tablePos=
0),b=c.table[a.tablePos],a.tablePos++,0<=b)?(f.pointer=c.pointer+(b<<5),d=0):-1!=b?c.tableDelay=b&127:a.tablePos=c.table[a.tablePos];while(d)}else a.tableCtr--;c.portamento&&(b=j[a.note]+a.pitchBend,0!=a.period?a.period<b?(a.period+=c.portamento,a.period>b&&(a.period=b)):(a.period-=c.portamento,a.period<b&&(a.period=b)):a.period=b);0==a.vibratoCtr?(a.vibratoPeriod=a.vibratoPos*c.vibratoStep,0==(a.status&1)?(a.vibratoPos++,a.vibratoPos==a.vibratoDir&&(a.status^=1)):(a.vibratoPos--,0==a.vibratoPos&&
(a.status^=1))):a.vibratoCtr--;a.pitchBend=0>c.pitchBend?a.pitchBend+c.pitchBend:a.pitchBend-c.pitchBend;if(a.row)switch(b=a.row,b.effect){case 1:if(b=b.param&15)this.speed=b;break;case 2:a.pitchBend-=b.param;break;case 3:a.pitchBend+=b.param;break;case 4:this.mixer.filter.active=b.param;break;case 5:c.vibratoWait=b.param;break;case 6:c.vibratoStep=b.param;case 7:c.vibratoLen=b.param;break;case 8:c.pitchBend=b.param;break;case 9:c.portamento=b.param;break;case 10:c.volume=64;break;case 11:c.arpeggio[0]=
b.param;break;case 12:c.arpeggio[1]=b.param;break;case 13:c.arpeggio[2]=b.param;break;case 14:c.arpeggio[3]=b.param;break;case 15:c.arpeggio[4]=b.param;break;case 16:c.arpeggio[5]=b.param;break;case 17:c.arpeggio[6]=b.param;break;case 18:c.arpeggio[7]=b.param;break;case 19:c.arpeggio[0]=c.arpeggio[4]=b.param;break;case 20:c.arpeggio[1]=c.arpeggio[5]=b.param;break;case 21:c.arpeggio[2]=c.arpeggio[6]=b.param;break;case 22:c.arpeggio[3]=c.arpeggio[7]=b.param;break;case 23:b=b.param;64<b&&(b=64);c.attackStep=
b;break;case 24:c.attackDelay=b.param;break;case 25:b=b.param;64<b&&(b=64);c.decayStep=b;break;case 26:c.decayDelay=b.param;break;case 27:c.sustain=b.param&c.sustain&255;break;case 28:c.sustain=(c.sustain&65280)+b.param;break;case 29:b=b.param;64<b&&(b=64);c.releaseStep=b;break;case 30:c.releaseDelay=b.param}c.portamento?b=a.period:(b=j[a.note+c.arpeggio[a.arpeggioPos]],a.arpeggioPos=++a.arpeggioPos&7,b-=c.vibratoLen*c.vibratoStep,b+=a.pitchBend,a.period=0);f.period=b+a.vibratoPeriod;d=a.status&14;
b=a.volume;0==d&&(0==a.attackCtr?(a.attackCtr=c.attackDelay,b+=c.attackStep,64<=b&&(d|=2,a.status|=2,b=64)):a.attackCtr--);2==d&&(0==a.decayCtr?(a.decayCtr=c.decayDelay,b-=c.decayStep,b<=c.volume&&(d|=6,a.status|=6,b=c.volume)):a.decayCtr--);6==d&&(0==a.sustain?(d|=14,a.status|=14):a.sustain--);14==d&&(0==a.releaseCtr?(a.releaseCtr=c.releaseDelay,b-=c.releaseStep,0>b&&(a.status&=9,b=0)):a.releaseCtr--);f.volume=a.volume=b;f.enabled=1;c.synth||(c.loop?(f.pointer=c.loopPtr,f.length=c.repeat):(f.pointer=
this.mixer.loopPtr,f.length=2));a=a.next}}}});f.voices[0]=h(0);f.voices[0].next=f.voices[1]=h(1);f.voices[1].next=f.voices[2]=h(2);f.voices[2].next=f.voices[3]=h(3);return Object.seal(f)}})();