/*
  Flod JS 2.1
  2012/04/30
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.0 - 2012/03/24

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function l(k,a){return Object.create(null,{index:{value:k,writable:!0},bitFlag:{value:a,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},trackPtr:{value:0,writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},frqseqPtr:{value:0,writable:!0},frqseqPos:{value:0,writable:!0},volseqPtr:{value:0,writable:!0},volseqPos:{value:0,writable:!0},volseqSpeed:{value:0,writable:!0},volseqCounter:{value:0,writable:!0},
halve:{value:0,writable:!0},speed:{value:0,writable:!0},tick:{value:0,writable:!0},busy:{value:0,writable:!0},flags:{value:0,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},transpose:{value:0,writable:!0},portaDelay:{value:0,writable:!0},portaDelta:{value:0,writable:!0},portaSpeed:{value:0,writable:!0},vibrato:{value:0,writable:!0},vibratoDelta:{value:0,writable:!0},vibratoSpeed:{value:0,writable:!0},vibratoDepth:{value:0,writable:!0},initialize:{value:function(){this.sample=
this.channel=null;this.speed=this.halve=this.volseqCounter=this.volseqSpeed=this.volseqPos=this.volseqPtr=this.frqseqPos=this.frqseqPtr=this.patternPos=this.trackPos=this.trackPtr=0;this.tick=1;this.busy=-1;this.vibratoDepth=this.vibratoSpeed=this.vibratoDelta=this.vibrato=this.portaSpeed=this.portaDelta=this.portaDelay=this.transpose=this.period=this.note=this.flags=0}}})}window.neoart.DWPlayer=function(k){k=AmigaPlayer(k);Object.defineProperties(k,{id:{value:"DWPlayer"},songs:{value:[],writable:!0},
samples:{value:[],writable:!0},stream:{value:null,writable:!0},song:{value:null,writable:!0},songvol:{value:0,writable:!0},master:{value:0,writable:!0},periods:{value:0,writable:!0},frqseqs:{value:0,writable:!0},volseqs:{value:0,writable:!0},transpose:{value:0,writable:!0},slower:{value:0,writable:!0},slowerCounter:{value:0,writable:!0},delaySpeed:{value:0,writable:!0},delayCounter:{value:0,writable:!0},fadeSpeed:{value:0,writable:!0},fadeCounter:{value:0,writable:!0},wave:{value:null,writable:!0},
waveCenter:{value:0,writable:!0},waveLo:{value:0,writable:!0},waveHi:{value:0,writable:!0},waveDir:{value:0,writable:!0},waveLen:{value:0,writable:!0},wavePos:{value:0,writable:!0},waveRateNeg:{value:0,writable:!0},waveRatePos:{value:0,writable:!0},voices:{value:[],writable:!0},active:{value:0,writable:!0},complete:{value:0,writable:!0},variant:{value:0,writable:!0},base:{value:0,writable:!0},com2:{value:0,writable:!0},com3:{value:0,writable:!0},com4:{value:0,writable:!0},readMix:{value:"",writable:!0},
readLen:{value:0,writable:!0},initialize:{value:function(){var a,d,f=this.voices[this.active];this.reset();this.song=this.songs[this.playSong];this.songvol=this.master;this.speed=this.song.speed;this.transpose=0;this.slowerCounter=6;this.delaySpeed=this.song.delay;this.fadeCounter=this.fadeSpeed=this.delayCounter=0;if(this.wave){this.waveDir=0;this.wavePos=this.wave.pointer+this.waveCenter;a=this.wave.pointer;for(d=this.wavePos;a<d;++a)this.mixer.memory[a]=this.waveRateNeg;for(d+=this.waveCenter;a<
d;++a)this.mixer.memory[a]=this.waveRatePos}for(;f;)f.initialize(),f.channel=this.mixer.channels[f.index],f.sample=this.samples[0],this.complete+=f.bitFlag,f.trackPtr=this.song.tracks[f.index],f.trackPos=this.readLen,this.stream.position=f.trackPtr,f.patternPos=this.base+this.stream[this.readMix](),this.frqseqs&&(this.stream.position=this.frqseqs,f.frqseqPtr=this.base+this.stream.readUshort(),f.frqseqPos=f.frqseqPtr),f=f.next}},loader:{value:function(a){var d,f,g,e,b,h,j=10,i,c;this.master=64;this.readMix=
"readUshort";this.readLen=2;this.variant=0;if(18663==a.readUshort()){a.position=4;if(24832!=a.readUshort())return;a.position+=a.readUshort();this.variant=30}else a.position=0;for(;20085!=c;){c=a.readUshort();switch(c){case 18426:this.base=a.position+a.readShort();break;case 24832:a.position+=2;b=a.position;24832==a.readUshort()&&(b=a.position+a.readUshort());break;case 49404:j=a.readUshort();18==j?(this.readMix="readUint",this.readLen=4):this.variant=10;16890==a.readUshort()&&(f=a.position+a.readUshort());
4656==a.readUshort()&&(d=1);break;case 4656:a.position-=6;16890==a.readUshort()&&(f=a.position+a.readUshort(),d=1);a.position+=4;break;case 48764:this.channels=a.readUshort(),a.position+=2,14204==a.readUshort()&&(this.master=a.readUshort())}if(20>a.bytesAvailable)return}e=a.position;this.songs=[];h=2147483647;i=0;for(a.position=f;;){f=Object.create(null,{speed:{value:0,writable:!0},delay:{value:0,writable:!0},tracks:{value:null,writable:!0}});f.tracks=new Uint32Array(this.channels);d?(f.speed=a.readUbyte(),
f.delay=a.readUbyte()):f.speed=a.readUshort();if(255<f.speed)break;for(g=0;g<this.channels;++g)c=this.base+a[this.readMix](),c<h&&(h=c),f.tracks[g]=c;this.songs[i++]=f;if(h-a.position<j)break}if(i&&(this.lastSong=this.songs.length-1,a.position=b,18987==a.readUshort())){f=j=0;for(this.wave=null;20085!=c;)switch(c=a.readUshort(),c){case 19450:if(f)break;b=a.position+a.readShort();a.position++;i=a.readUbyte();a.position-=10;c=a.readUshort();d=a.position;16890==c||8314==c?f=a.position+a.readUshort():
53500==c&&(f=64+a.readUshort(),a.position-=18,f+=a.position+a.readUshort());a.position=d;break;case 33987:if(j)break;a.position+=4;c=a.readUshort();56060==c?j=a.readUshort():56316==c&&(j=a.readUint());12==j&&30>this.variant&&(this.variant=20);d=a.position;this.samples=[];this.samples.length=++i;a.position=f;for(g=0;g<i;++g)c=AmigaSample(),Object.defineProperties(c,{relative:{value:0,writable:!0},finetune:{value:0,writable:!0}}),h=Object.seal(c),h.length=a.readUint(),h.relative=parseInt(3579545/a.readUshort()),
h.pointer=this.mixer.store(a,h.length),c=a.position,a.position=b+g*j+4,h.loopPtr=a.readInt(),0==this.variant?(a.position+=6,h.volume=a.readUshort()):10==this.variant&&(a.position+=4,h.volume=a.readUshort(),h.finetune=a.readByte()),a.position=c,this.samples[g]=h;this.mixer.loopLen=64;a.length=f;a.position=d;break;case 8314:c=a.position+a.readShort();if(12860!=a.readUshort()){a.position-=2;break}this.wave=this.samples[parseInt((c-b)/j)];this.waveCenter=a.readUshort()+1<<1;a.position+=2;this.waveRateNeg=
a.readByte();a.position+=12;this.waveRatePos=a.readByte();break;case 1131:case 1643:i=a.readUshort(),h=this.samples[parseInt((a.readUshort()-b)/j)],h.relative=1643==c?h.relative+i:h.relative-i}if(this.samples.length){a.position=e;this.slower=this.volseqs=this.frqseqs=this.periods=0;this.com2=176;this.com3=160;for(this.com4=144;16<a.bytesAvailable;)switch(c=a.readUshort(),c){case 18426:a.position+=2;if(18987!=a.readUshort())break;d=a.position;a.position+=4;c=a.readUshort();if(4154==c){if(a.position+=
4,49404==a.readUshort()){c=a.readUshort();i=this.songs.length;for(g=0;g<i;++g)this.songs[g].delay*=c;a.position+=6}}else 21291==c&&(a.position-=8);c=a.readUshort();18987==c&&(a.position=this.base+a.readUshort(),this.slower=a.readByte());a.position=d;break;case 3179:a.position-=6;c=a.readUshort();if(21611==c||21099==c)a.position+=4,this.waveHi=this.wave.pointer+a.readUshort();else if(21867==c||21355==c)a.position+=4,this.waveLo=this.wave.pointer+a.readUshort();this.waveLen=21611>c?1:2;break;case 32256:case 32257:case 32258:case 32259:this.active=
c&15;i=this.channels-1;if(this.active){this.voices[0].next=null;for(g=i;0<g;)this.voices[g].next=this.voices[--g]}else{this.voices[i].next=null;for(g=0;g<i;)this.voices[g].next=this.voices[++g]}break;case 3176:a.position+=22;3089==a.readUshort()&&(this.variant=40);break;case 12845:d=a.position;c=a.readUshort();if(10==c||12==c)a.position-=8,17914==a.readUshort()&&(this.periods=a.position+a.readUshort());a.position=d+2;break;case 1024:case 1088:case 1536:c=a.readUshort();192==c||64==c?(this.com2=192,
this.com3=176,this.com4=160):c==this.com3?(a.position+=2,17914==a.readUshort()&&(this.volseqs=a.position+a.readUshort(),40>this.variant&&(this.variant=30))):c==this.com4&&(a.position+=2,17914==a.readUshort()&&(this.frqseqs=a.position+a.readUshort()));break;case 20211:a.position+=2;case 20178:if(h=a.position,a.position-=10,a.position+=a.readUshort(),d=a.position,a.position=d+2,a.position=this.base+a.readUshort()+10,18964==a.readUshort()&&(this.variant=41),a.position=d+16,c=this.base+a.readUshort(),
c>h&&c<d&&(a.position=c,c=a.readUshort(),20712==c?this.variant=21:5977==c&&(this.variant=11)),a.position=d+20,c=this.base+a.readUshort(),c>h&&c<d&&(a.position=c+2,18560!=a.readUshort()&&(this.variant=31)),a.position=d+26,c=a.readUshort(),c>h&&c<d&&(this.variant=32),this.frqseqs)a.position=a.length}this.periods&&(this.com2-=256,this.com3-=256,this.com4-=256,this.stream=a,this.version=1)}}}},process:{value:function(){var a,d,f,g,e,b=this.voices[this.active];if(this.slower&&0==--this.slowerCounter)this.slowerCounter=
6;else if(255<(this.delayCounter+=this.delaySpeed))this.delayCounter-=256;else{if(this.fadeSpeed&&(0==--this.fadeCounter&&(this.fadeCounter=this.fadeSpeed,this.songvol--),!this.songvol))if(this.loopSong)this.initialize();else{this.mixer.complete=1;return}if(this.wave)if(this.waveDir){if(this.mixer.memory[this.wavePos++]=this.waveRatePos,1<this.waveLen&&(this.mixer.memory[this.wavePos++]=this.waveRatePos),(this.wavePos-=this.waveLen<<1)==this.waveLo)this.waveDir=0}else if(this.mixer.memory[this.wavePos++]=
this.waveRateNeg,1<this.waveLen&&(this.mixer.memory[this.wavePos++]=this.waveRateNeg),this.wavePos==this.waveHi)this.waveDir=1;for(;b;){a=b.channel;this.stream.position=b.patternPos;g=b.sample;b.busy||(b.busy=1,0>g.loopPtr?(a.pointer=this.mixer.loopPtr,a.length=this.mixer.loopLen):(a.pointer=g.pointer+g.loopPtr,a.length=g.length-g.loopPtr));if(0==--b.tick){b.flags=0;for(d=1;0<d;)if(e=this.stream.readByte(),0>e)if(-32<=e)b.speed=this.speed*(e+33);else if(e>=this.com2)e-=this.com2,b.sample=g=this.samples[e];
else if(e>=this.com3)f=this.stream.position,this.stream.position=this.volseqs+(e-this.com3<<1),this.stream.position=this.base+this.stream.readUshort(),b.volseqPtr=this.stream.position,this.stream.position--,b.volseqSpeed=this.stream.readUbyte(),this.stream.position=f;else if(e>=this.com4)f=this.stream.position,this.stream.position=this.frqseqs+(e-this.com4<<1),b.frqseqPtr=this.base+this.stream.readUshort(),b.frqseqPos=b.frqseqPtr,this.stream.position=f;else switch(e){case -128:this.stream.position=
b.trackPtr+b.trackPos;(e=this.stream[this.readMix]())?(this.stream.position=this.base+e,b.trackPos+=this.readLen):(this.stream.position=b.trackPtr,this.stream.position=this.base+this.stream[this.readMix](),b.trackPos=this.readLen,this.loopSong||(this.complete&=~b.bitFlag,this.complete||(this.mixer.complete=1)));break;case -127:0<this.variant&&(b.portaDelta=0);b.portaSpeed=this.stream.readByte();b.portaDelay=this.stream.readUbyte();b.flags|=2;break;case -126:b.tick=b.speed;b.patternPos=this.stream.position;
41==this.variant?(b.busy=1,a.enabled=0):(a.pointer=this.mixer.loopPtr,a.length=this.mixer.loopLen);d=0;break;case -125:0<this.variant&&(b.tick=b.speed,b.patternPos=this.stream.position,a.enabled=1,d=0);break;case -124:this.mixer.complete=1;break;case -123:0<this.variant&&(this.transpose=this.stream.readByte());break;case -122:b.vibrato=-1;b.vibratoSpeed=this.stream.readUbyte();b.vibratoDepth=this.stream.readUbyte();b.vibratoDelta=0;break;case -121:b.vibrato=0;break;case -120:21==this.variant?b.halve=
1:11==this.variant?this.fadeSpeed=this.stream.readUbyte():b.transpose=this.stream.readByte();break;case -119:21==this.variant?b.halve=0:(b.trackPtr=this.base+this.stream.readUshort(),b.trackPos=0);break;case -118:31==this.variant?this.delaySpeed=this.stream.readUbyte():this.speed=this.stream.readUbyte();break;case -117:this.fadeCounter=this.fadeSpeed=this.stream.readUbyte();break;case -116:e=this.stream.readUbyte(),32!=this.variant&&(this.songvol=e)}else b.patternPos=this.stream.position,b.note=e+=
g.finetune,b.tick=b.speed,b.busy=0,20<=this.variant?(e=e+this.transpose+b.transpose&255,this.stream.position=b.volseqPtr,d=this.stream.readUbyte(),b.volseqPos=this.stream.position,b.volseqCounter=b.volseqSpeed,b.halve&&(d>>=1),d=d*this.songvol>>6):d=g.volume,a.pointer=g.pointer,a.length=g.length,a.volume=d,this.stream.position=this.periods+(e<<1),e=this.stream.readUshort()*g.relative>>10,10>this.variant&&(b.portaDelta=e),a.period=e,a.enabled=1,d=0}else if(1==b.tick)if(30>this.variant)a.enabled=0;
else{if(e=this.stream.readUbyte(),131!=e&&(40>this.variant||224>e||131!=this.stream.readUbyte()))a.enabled=0}else 0==this.variant?b.flags&2&&(b.portaDelay?b.portaDelay--:(b.portaDelta-=b.portaSpeed,a.period=b.portaDelta)):(this.stream.position=b.frqseqPos,e=this.stream.readByte(),0>e&&(e&=127,this.stream.position=b.frqseqPtr),b.frqseqPos=this.stream.position,e=e+b.note+this.transpose+b.transpose&255,this.stream.position=this.periods+(e<<1),e=this.stream.readUshort()*g.relative>>10,b.flags&2&&(b.portaDelay?
b.portaDelay--:(b.portaDelta+=b.portaSpeed,e-=b.portaDelta)),b.vibrato&&(0<b.vibrato?(b.vibratoDelta-=b.vibratoSpeed,b.vibratoDelta||(b.vibrato^=2147483648)):(b.vibratoDelta+=b.vibratoSpeed,b.vibratoDelta==b.vibratoDepth&&(b.vibrato^=2147483648)),b.vibratoDelta||(b.vibrato^=1),e=b.vibrato&1?e+b.vibratoDelta:e-b.vibratoDelta),a.period=e,20<=this.variant&&0>--b.volseqCounter&&(this.stream.position=b.volseqPos,d=this.stream.readByte(),0<=d&&(b.volseqPos=this.stream.position),b.volseqCounter=b.volseqSpeed,
d&=127,b.halve&&(d>>=1),a.volume=d*this.songvol>>6));b=b.next}}}}});k.voices[0]=l(0,1);k.voices[1]=l(1,2);k.voices[2]=l(2,4);k.voices[3]=l(3,8);return Object.seal(k)}})();