/*
  Flod JS 2.1
  2012/04/30
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.1 - 2012/04/16

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function h(f){return Object.create(null,{index:{value:f,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},enabled:{value:0,writable:!0},period:{value:0,writable:!0},effect:{value:0,writable:!0},param:{value:0,writable:!0},volume:{value:0,writable:!0},portaDir:{value:0,writable:!0},portaPeriod:{value:0,writable:!0},portaSpeed:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},vibratoSpeed:{value:0,writable:!0},initialize:{value:function(){this.sample=
this.channel=null;this.vibratoSpeed=this.vibratoPos=this.portaSpeed=this.portaPeriod=this.portaDir=this.volume=this.param=this.effect=this.period=this.enabled=0}}})}var i=[856,808,762,720,678,640,604,570,538,508,480,453,428,404,381,360,339,320,302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,0],j=[0,24,49,74,97,120,141,161,180,197,212,224,235,244,250,253,255,253,250,244,235,224,212,197,180,161,141,120,97,74,49,24];window.neoart.MKPlayer=function(f){f=AmigaPlayer(f);Object.defineProperties(f,
{id:{value:"MKPlayer"},track:{value:null,writable:!0},patterns:{value:[],writable:!0},samples:{value:[],writable:!0},length:{value:0,writable:!0},restart:{value:0,writable:!0},voices:{value:[],writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},jumpFlag:{value:0,writable:!0},vibratoDepth:{value:0,writable:!0},restartSave:{value:0,writable:!0},force:{set:function(b){1>b?b=1:5<b&&(b=5);this.version=b;this.vibratoDepth=5==b?6:7;3==b?(this.restartSave=this.restart,this.restart=
0):(this.restart=this.restartSave,this.restartSave=0)}},initialize:{value:function(){var b=this.voices[0];this.reset();this.force=this.version;this.speed=6;for(this.jumpFlag=this.patternPos=this.trackPos=0;b;)b.initialize(),b.channel=this.mixer.channels[b.index],b.sample=this.samples[0],b=b.next}},loader:{value:function(b){var f=0,e,c,d=0,g;if(!(2106>b.length)&&(b.position=1080,e=b.readString(4),!("M.K."!=e&&"FLT4"!=e))){b.position=0;this.title=b.readString(20);this.version=1;b.position+=22;for(e=
1;32>e;++e)(g=b.readUshort())?(c=AmigaSample(),b.position-=24,c.name=b.readString(22),c.length=g<<1,b.position+=3,c.volume=b.readUbyte(),c.loop=b.readUshort()<<1,c.repeat=b.readUshort()<<1,b.position+=22,c.pointer=d,d+=c.length,this.samples[e]=c,32768<c.length&&(this.version=2)):(this.samples[e]=null,b.position+=28);b.position=950;this.length=b.readUbyte();g=b.readUbyte();this.restart=g<length?g:0;for(e=0;128>e;++e)g=b.readUbyte()<<8,this.track[e]=g,g>f&&(f=g);b.position=1084;f+=256;this.patterns.length=
f;for(e=0;e<f;++e){c=AmigaRow();g=b.readUint();c.note=g>>16&4095;c.effect=g>>8&15;c.sample=g>>24&240|g>>12&15;c.param=g&255;this.patterns[e]=c;if(31<c.sample||!this.samples[c.sample])c.sample=0;if(3==c.effect||4==c.effect)this.version=3;if(5==c.effect||6==c.effect)this.version=5;if(6<c.effect&&10>c.effect){this.version=0;return}}this.mixer.store(b,d);for(e=1;32>e;++e)if(c=this.samples[e]){-1<c.name.indexOf("2.0")&&(this.version=5);c.loop?(c.loopPtr=c.pointer+c.loop,c.length=c.loop+c.repeat):(c.loopPtr=
this.mixer.memory.length,c.repeat=2);d=c.pointer+4;for(b=c.pointer;b<d;++b)this.mixer.memory[b]=0}c=AmigaSample();c.pointer=c.loopPtr=this.mixer.memory.length;c.length=c.repeat=2;this.samples[0]=c;5>this.version&&this.restart&&(this.version=4)}}},process:{value:function(){var b,f,e,c,d,g,a=this.voices[0];if(this.tick)for(;a;){b=a.channel;if(!a.effect&&!a.param)b.period=a.period;else{switch(a.effect){case 0:d=this.tick%3;if(!d){b.period=a.period;a=a.next;continue}d=1==d?a.param>>4:a.param&15;c=a.period&
4095;e=37-d;for(f=0;f<e;++f)if(c>=i[f]){b.period=i[f+d];break}break;case 1:a.period-=a.param;113>a.period&&(a.period=113);b.period=a.period;break;case 2:a.period+=a.param;856<a.period&&(a.period=856);b.period=a.period;break;case 3:case 5:5==a.effect?g=1:a.param&&(a.portaSpeed=a.param,a.param=0);a.portaPeriod&&(a.portaDir?(a.period-=a.portaSpeed,a.period<=a.portaPeriod&&(a.period=a.portaPeriod,a.portaPeriod=0)):(a.period+=a.portaSpeed,a.period>=a.portaPeriod&&(a.period=a.portaPeriod,a.portaPeriod=
0)));b.period=a.period;break;case 4:case 6:6==a.effect?g=1:a.param&&(a.vibratoSpeed=a.param);d=a.vibratoPos>>2&31;d=(a.vibratoSpeed&15)*j[d]>>this.vibratoDepth;b.period=127<a.vibratoPos?a.period-d:a.period+d;d=a.vibratoSpeed>>2&60;a.vibratoPos=a.vibratoPos+d&255;break;case 10:g=1}g&&(d=a.param>>4,g=0,a.volume=d?a.volume+d:a.volume-(a.param&15),0>a.volume?a.volume=0:64<a.volume&&(a.volume=64),b.volume=a.volume)}a=a.next}else for(f=this.track[this.trackPos]+this.patternPos;a;){b=a.channel;a.enabled=
0;d=this.patterns[f+a.index];a.effect=d.effect;a.param=d.param;d.sample?(e=a.sample=this.samples[d.sample],b.volume=a.volume=e.volume):e=a.sample;d.note&&(3==a.effect||5==a.effect?d.note<a.period?(a.portaDir=1,a.portaPeriod=d.note):d.note>a.period?(a.portaDir=0,a.portaPeriod=d.note):a.portaPeriod=0:(a.enabled=1,a.vibratoPos=0,b.enabled=0,b.pointer=e.pointer,b.length=e.length,b.period=a.period=d.note));switch(a.effect){case 11:this.trackPos=a.param-1;this.jumpFlag^=1;break;case 12:b.volume=a.param;
5==this.version&&(a.volume=a.param);break;case 13:this.jumpFlag^=1;break;case 14:this.mixer.filter.active=a.param^1;break;case 15:d=a.param,1>d?d=1:31<d&&(d=31),this.speed=d,this.tick=0}a.enabled&&(b.enabled=1);b.pointer=e.loopPtr;b.length=e.repeat;a=a.next}if(++this.tick==this.speed&&(this.tick=0,this.patternPos+=4,256==this.patternPos||this.jumpFlag))this.patternPos=this.jumpFlag=0,this.trackPos=++this.trackPos&127,this.trackPos==this.length&&(this.trackPos=this.restart,this.mixer.complete=1)}}});
f.voices[0]=h(0);f.voices[0].next=f.voices[1]=h(1);f.voices[1].next=f.voices[2]=h(2);f.voices[2].next=f.voices[3]=h(3);f.track=new Uint16Array(128);return Object.seal(f)}})();