/*
  Flod JS 2.0
  2012/04/01
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.0 - 2012/03/11

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function j(i){return Object.create(null,{index:{value:i,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},enabled:{value:0,writable:!0},restart:{value:0,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},sample:{value:0,writable:!0},samplePtr:{value:0,writable:!0},sampleLen:{value:0,writable:!0},synth:{value:0,writable:!0},synthPtr:{value:0,writable:!0},arpeggio:{value:0,writable:!0},autoArpeggio:{value:0,writable:!0},autoSlide:{value:0,writable:!0},
vibrato:{value:0,writable:!0},volume:{value:0,writable:!0},volumeDef:{value:0,writable:!0},adsrControl:{value:0,writable:!0},adsrPtr:{value:0,writable:!0},adsrCtr:{value:0,writable:!0},lfoControl:{value:0,writable:!0},lfoPtr:{value:0,writable:!0},lfoCtr:{value:0,writable:!0},egControl:{value:0,writable:!0},egPtr:{value:0,writable:!0},egCtr:{value:0,writable:!0},egValue:{value:0,writable:!0},fxControl:{value:0,writable:!0},fxCtr:{value:0,writable:!0},modControl:{value:0,writable:!0},modPtr:{value:0,
writable:!0},modCtr:{value:0,writable:!0},initialize:{value:function(){this.channel=null;this.samplePtr=this.sample=this.period=this.note=this.restart=this.enabled=0;this.sampleLen=2;this.synth=0;this.synthPtr=-1;this.modCtr=this.modPtr=this.modControl=this.fxCtr=this.fxControl=this.egValue=this.egCtr=this.egPtr=this.egControl=this.lfoCtr=this.lfoPtr=this.lfoControl=this.adsrCtr=this.adsrPtr=this.adsrControl=this.volumeDef=this.volume=this.vibrato=this.autoSlide=this.autoArpeggio=this.arpeggio=0}}})}
var k=[6848,6464,6080,5760,5440,5120,4832,4576,4320,4064,3840,3616,3424,3232,3040,2880,2720,2560,2416,2288,2160,2032,1920,1808,1712,1616,1520,1440,1360,1280,1208,1144,1080,1016,960,904,856,808,760,720,680,640,604,572,540,508,480,452,428,404,380,360,340,320,302,286,270,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,107,101,95,90,85,80,76,72,68,64,60,57],l=[0,64,128,64,0,-64,-128,-64];window.neoart.BPPlayer=function(i){i=AmigaPlayer(i);Object.defineProperties(i,{id:{value:"BPPlayer"},tracks:{value:[],
writable:!0},patterns:{value:[],writable:!0},samples:{value:[],writable:!0},length:{value:0,writable:!0},buffer:{value:null,writable:!0},voices:{value:[],writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},nextPos:{value:0,writable:!0},jumpFlag:{value:0,writable:!0},repeatCtr:{value:0,writable:!0},arpeggioCtr:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},initialize:{value:function(){var c,d=this.voices[0];this.reset();this.speed=6;this.tick=1;this.repeatCtr=this.jumpFlag=
this.nextPos=this.patternPos=this.trackPos=0;this.arpeggioCtr=1;for(c=this.vibratoPos=0;128>c;++c)this.buffer[c]=0;for(;d;)d.initialize(),d.channel=this.mixer.channels[d.index],d.samplePtr=this.mixer.loopPtr,d=d.next}},restore:{value:function(){for(var c,d,e,b=this.voices[0];b;){if(-1<b.synthPtr){e=b.index<<5;d=b.synthPtr+32;for(c=b.synthPtr;c<d;++c)this.mixer.memory[c]=this.buffer[e++]}b=b.next}}},loader:{value:function(c){var d=0,e=0,b,g,f;this.title=c.readString(26);b=c.readString(4);if("BPSM"==
b)this.version=1;else{b=b.substr(0,3);if("V.2"==b)this.version=2;else if("V.3"==b)this.version=3;else return;c.position=29;f=c.readUbyte()}for(this.length=c.readUshort();16>++e;)b=AmigaSample(),Object.defineProperties(b,{synth:{value:0,writable:!0},table:{value:0,writable:!0},adsrControl:{value:0,writable:!0},adsrTable:{value:0,writable:!0},adsrLen:{value:0,writable:!0},adsrSpeed:{value:0,writable:!0},lfoControl:{value:0,writable:!0},lfoTable:{value:0,writable:!0},lfoDepth:{value:0,writable:!0},lfoLen:{value:0,
writable:!0},lfoDelay:{value:0,writable:!0},lfoSpeed:{value:0,writable:!0},egControl:{value:0,writable:!0},egTable:{value:0,writable:!0},egLen:{value:0,writable:!0},egDelay:{value:0,writable:!0},egSpeed:{value:0,writable:!0},fxControl:{value:0,writable:!0},fxDelay:{value:0,writable:!0},fxSpeed:{value:0,writable:!0},modControl:{value:0,writable:!0},modTable:{value:0,writable:!0},modLen:{value:0,writable:!0},modDelay:{value:0,writable:!0},modSpeed:{value:0,writable:!0}}),b=Object.seal(b),255==c.readUbyte()?
(b.synth=1,b.table=c.readUbyte(),b.pointer=b.table<<6,b.length=c.readUshort()<<1,b.adsrControl=c.readUbyte(),b.adsrTable=c.readUbyte()<<6,b.adsrLen=c.readUshort(),b.adsrSpeed=c.readUbyte(),b.lfoControl=c.readUbyte(),b.lfoTable=c.readUbyte()<<6,b.lfoDepth=c.readUbyte(),b.lfoLen=c.readUshort(),3>this.version?(c.readByte(),b.lfoDelay=c.readUbyte(),b.lfoSpeed=c.readUbyte(),b.egControl=c.readUbyte(),b.egTable=c.readUbyte()<<6,c.readByte(),b.egLen=c.readUshort(),c.readByte(),b.egDelay=c.readUbyte(),b.egSpeed=
c.readUbyte(),b.fxSpeed=1,b.modSpeed=1,b.volume=c.readUbyte(),c.position+=6):(b.lfoDelay=c.readUbyte(),b.lfoSpeed=c.readUbyte(),b.egControl=c.readUbyte(),b.egTable=c.readUbyte()<<6,b.egLen=c.readUshort(),b.egDelay=c.readUbyte(),b.egSpeed=c.readUbyte(),b.fxControl=c.readUbyte(),b.fxSpeed=c.readUbyte(),b.fxDelay=c.readUbyte(),b.modControl=c.readUbyte(),b.modTable=c.readUbyte()<<6,b.modSpeed=c.readUbyte(),b.modDelay=c.readUbyte(),b.volume=c.readUbyte(),b.modLen=c.readUshort())):(c.position--,b.synth=
0,b.name=c.readString(24),b.length=c.readUshort()<<1,b.length?(b.loop=c.readUshort(),b.repeat=c.readUshort()<<1,b.volume=c.readUshort(),b.loop+b.repeat>=b.length&&(b.repeat=b.length-b.loop)):(b.pointer--,b.repeat=2,c.position+=6)),this.samples[e]=b;b=this.length<<2;this.tracks.length=b;for(e=0;e<b;++e)g=AmigaStep(),Object.defineProperties(g,{soundTranspose:{value:0,writable:!0}}),g=Object.seal(g),g.pattern=c.readUshort(),g.soundTranspose=c.readByte(),g.transpose=c.readByte(),g.pattern>d&&(d=g.pattern),
this.tracks[e]=g;b=d<<4;this.patterns.length=b;for(e=0;e<b;++e)d=AmigaRow(),d.note=c.readByte(),d.sample=c.readUbyte(),d.effect=d.sample&15,d.sample=(d.sample&240)>>4,d.param=c.readByte(),this.patterns[e]=d;this.mixer.store(c,f<<6);for(e=0;16>++e;)b=this.samples[e],!b.synth&&b.length&&(b.pointer=this.mixer.store(c,b.length),b.loopPtr=b.pointer+b.loop)}},process:{value:function(){var c,d,e,b,g,f=this.mixer.memory,h,a=this.voices[0];this.arpeggioCtr=--this.arpeggioCtr&3;for(this.vibratoPos=++this.vibratoPos&
7;a;){c=a.channel;a.period+=a.autoSlide;c.period=a.vibrato?a.period+(l[this.vibratoPos]/a.vibrato>>0):a.period;c.pointer=a.samplePtr;c.length=a.sampleLen;if(a.arpeggio||a.autoArpeggio)b=a.note,this.arpeggioCtr?1==this.arpeggioCtr&&(b+=(a.arpeggio&15)+(a.autoArpeggio&15)):b+=((a.arpeggio&240)>>4)+((a.autoArpeggio&240)>>4),c.period=a.period=k[b+35],a.restart=0;if(a.synth&&!(0>a.sample)&&(b=this.samples[a.sample],a.adsrControl&&0==--a.adsrCtr&&(a.adsrCtr=b.adsrSpeed,d=128+f[b.adsrTable+a.adsrPtr]>>2,
c.volume=d*a.volume>>6,++a.adsrPtr==b.adsrLen&&(a.adsrPtr=0,1==a.adsrControl&&(a.adsrControl=0))),a.lfoControl&&0==--a.lfoCtr&&(a.lfoCtr=b.lfoSpeed,d=f[b.lfoTable+a.lfoPtr],b.lfoDepth&&(d=d/b.lfoDepth>>0),c.period=a.period+d,++a.lfoPtr==b.lfoLen&&(a.lfoPtr=0,1==a.lfoControl&&(a.lfoControl=0))),!(0>a.synthPtr))){if(a.egControl&&0==--a.egCtr){a.egCtr=b.egSpeed;d=a.egValue;a.egValue=128+f[b.egTable+a.egPtr]>>3;if(a.egValue!=d)if(h=(a.index<<5)+d,e=a.synthPtr+d,a.egValue<d){d-=a.egValue;for(g=e-d;e>g;)f[--e]=
this.buffer[--h]}else{d=a.egValue-d;for(g=e+d;e<g;)f[e++]=~this.buffer[h++]+1}++a.egPtr==b.egLen&&(a.egPtr=0,1==a.egControl&&(a.egControl=0))}switch(a.fxControl){case 1:if(0==--a.fxCtr){a.fxCtr=b.fxSpeed;e=a.synthPtr;g=a.synthPtr+32;for(d=0<e?f[e-1]:0;e<g;)d=d+f[e+1]>>1,f[e++]=d}break;case 2:h=(a.index<<5)+31;g=a.synthPtr+32;d=b.fxSpeed;for(e=a.synthPtr;e<g;++e)this.buffer[h]<f[e]?f[e]-=d:this.buffer[h]>f[e]&&(f[e]+=d),h--;break;case 3:case 5:h=a.index<<5;g=a.synthPtr+32;d=b.fxSpeed;for(e=a.synthPtr;e<
g;++e)this.buffer[h]<f[e]?f[e]-=d:this.buffer[h]>f[e]&&(f[e]+=d),h++;break;case 4:h=a.synthPtr+64;g=a.synthPtr+32;d=b.fxSpeed;for(e=a.synthPtr;e<g;++e)f[h]<f[e]?f[e]-=d:f[h]>f[e]&&(f[e]+=d),h++;break;case 6:if(0==--a.fxCtr){a.fxControl=0;a.fxCtr=1;h=a.synthPtr+64;g=a.synthPtr+32;for(e=a.synthPtr;e<g;++e)f[e]=f[h++]}}a.modControl&&0==--a.modCtr&&(a.modCtr=b.modSpeed,f[a.synthPtr+32]=f[b.modTable+a.modPtr],++a.modPtr==b.modLen&&(a.modPtr=0,1==a.modControl&&(a.modControl=0)))}a=a.next}if(0==--this.tick){this.tick=
this.speed;for(a=this.voices[0];a;){c=a.channel;a.enabled=0;g=this.tracks[(this.trackPos<<2)+a.index];h=this.patterns[this.patternPos+(g.pattern-1<<4)];b=h.note;e=h.effect;d=h.param;if(b){a.autoArpeggio=a.autoSlide=a.vibrato=0;if(10!=e||0==(d&240))b+=g.transpose;a.note=b;a.period=k[b+35];a.restart=13>e?a.volumeDef=1:0;b=h.sample;0==b&&(b=a.sample);if(10!=e||0==(d&15))b+=g.soundTranspose;if(13>e&&(!a.synth||a.sample!=b))a.sample=b,a.enabled=1}switch(e){case 0:a.arpeggio=d;break;case 1:a.volume=d;a.volumeDef=
0;if(3>this.version||!a.synth)c.volume=a.volume;break;case 2:this.tick=this.speed=d;break;case 3:this.mixer.filter.active=d;break;case 4:a.period-=d;a.arpeggio=0;break;case 5:a.period+=d;a.arpeggio=0;break;case 6:3==this.version?a.vibrato=d:this.repeatCtr=d;break;case 7:3==this.version?(this.nextPos=d,this.jumpFlag=1):0==this.repeatCtr&&(this.trackPos=d);break;case 8:a.autoSlide=d;break;case 9:a.autoArpeggio=d;3==this.version&&(a.adsrPtr=0,0==a.adsrControl&&(a.adsrControl=1));break;case 11:a.fxControl=
d;break;case 13:a.autoArpeggio=d;a.fxControl^=1;a.adsrPtr=0;0==a.adsrControl&&(a.adsrControl=1);break;case 14:a.autoArpeggio=d;a.adsrPtr=0;0==a.adsrControl&&(a.adsrControl=1);break;case 15:a.autoArpeggio=d}a=a.next}this.jumpFlag?(this.trackPos=this.nextPos,this.patternPos=this.jumpFlag=0):16==++this.patternPos&&(this.patternPos=0,++this.trackPos==this.length&&(this.trackPos=0,this.mixer.complete=1));for(a=this.voices[0];a;){c=a.channel;a.enabled&&(c.enabled=a.enabled=0);if(0!=a.restart&&-1<a.synthPtr){h=
a.index<<5;g=a.synthPtr+32;for(e=a.synthPtr;e<g;++e)f[e]=this.buffer[h++];a.synthPtr=-1}a=a.next}for(a=this.voices[0];a;){if(!(0==a.restart||0>a.sample)){c=a.channel;c.period=a.period;a.restart=0;b=this.samples[a.sample];if(b.synth){if(a.synth=1,a.egValue=0,a.adsrPtr=a.lfoPtr=a.egPtr=a.modPtr=0,a.adsrCtr=1,a.lfoCtr=b.lfoDelay+1,a.egCtr=b.egDelay+1,a.fxCtr=b.fxDelay+1,a.modCtr=b.modDelay+1,a.adsrControl=b.adsrControl,a.lfoControl=b.lfoControl,a.egControl=b.egControl,a.fxControl=b.fxControl,a.modControl=
b.modControl,c.pointer=a.samplePtr=b.pointer,c.length=a.sampleLen=b.length,a.adsrControl?(d=128+f[b.adsrTable]>>2,a.volumeDef&&(a.volume=b.volume,a.volumeDef=0),c.volume=d*a.volume>>6):c.volume=a.volumeDef?b.volume:a.volume,a.egControl||a.fxControl||a.modControl){a.synthPtr=b.pointer;e=a.index<<5;g=a.synthPtr+32;for(h=a.synthPtr;h<g;++h)this.buffer[e++]=f[h]}}else a.synth=a.lfoControl=0,0>b.pointer?(a.samplePtr=this.mixer.loopPtr,a.sampleLen=2):(c.pointer=b.pointer,c.volume=a.volumeDef?b.volume:a.volume,
2!=b.repeat?(a.samplePtr=b.loopPtr,c.length=a.sampleLen=b.repeat):(a.samplePtr=this.mixer.loopPtr,a.sampleLen=2,c.length=b.length));c.enabled=a.enabled=1}a=a.next}}}}});i.voices[0]=j(0);i.voices[0].next=i.voices[1]=j(1);i.voices[1].next=i.voices[2]=j(2);i.voices[2].next=i.voices[3]=j(3);i.buffer=new Int8Array(128);return Object.seal(i)}})();