/*
  Flod JS 2.0
  2012/04/01
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.0 - 2012/03/24

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function k(i,b){return Object.create(null,{index:{value:i,writable:!0},bitFlag:{value:b,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},sample:{value:null,writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},tick:{value:0,writable:!0},busy:{value:0,writable:!0},synth:{value:0,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},volume:{value:0,writable:!0},envelopePos:{value:0,writable:!0},sustainTime:{value:0,writable:!0},
arpeggioPos:{value:0,writable:!0},arpeggioSpeed:{value:0,writable:!0},portamento:{value:0,writable:!0},portaCounter:{value:0,writable:!0},portaDelay:{value:0,writable:!0},portaFlag:{value:0,writable:!0},portaLimit:{value:0,writable:!0},portaNote:{value:0,writable:!0},portaPeriod:{value:0,writable:!0},portaSpeed:{value:0,writable:!0},vibrato:{value:0,writable:!0},vibratoDelay:{value:0,writable:!0},vibratoDepth:{value:0,writable:!0},vibratoFlag:{value:0,writable:!0},vibratoSpeed:{value:0,writable:!0},
pulseCounter:{value:0,writable:!0},pulseDelay:{value:0,writable:!0},pulseDir:{value:0,writable:!0},pulsePos:{value:0,writable:!0},pulseSpeed:{value:0,writable:!0},blendCounter:{value:0,writable:!0},blendDelay:{value:0,writable:!0},blendDir:{value:0,writable:!0},blendPos:{value:0,writable:!0},initialize:{value:function(){this.sample=this.channel=null;this.patternPos=this.trackPos=0;this.busy=this.tick=1;this.blendPos=this.blendDir=this.blendDelay=this.blendCounter=this.pulseSpeed=this.pulsePos=this.pulseDir=
this.pulseDelay=this.pulseCounter=this.vibratoSpeed=this.vibratoFlag=this.vibratoDepth=this.vibratoDelay=this.vibrato=this.portaSpeed=this.portaPeriod=this.portaNote=this.portaLimit=this.portaFlag=this.portaDelay=this.portaCounter=this.portamento=this.arpeggioSpeed=this.arpeggioPos=this.sustainTime=this.envelopePos=this.volume=this.period=this.note=0}}})}var l=[8192,7728,7296,6888,6504,6136,5792,5464,5160,4872,4600,4336,4096,3864,3648,3444,3252,3068,2896,2732,2580,2436,2300,2168,2048,1932,1824,1722,
1626,1534,1448,1366,1290,1218,1150,1084,1024,966,912,861,813,767,724,683,645,609,575,542,512,483,456,430,406,383,362,341,322,304,287,271,256,241,228,215,203,191,181,170,161,152,143,135];window.neoart.FEPlayer=function(i){i=AmigaPlayer(i);Object.defineProperties(i,{id:{value:"FEPlayer"},songs:{value:[],writable:!0},samples:{value:[],writable:!0},patterns:{value:null,writable:!0},song:{value:null,writable:!0},voices:{value:[],writable:!0},complete:{value:0,writable:!0},sampFlag:{value:0,writable:!0},
initialize:{value:function(){var b,f,e=this.voices[3];this.reset();this.song=this.songs[this.playSong];this.speed=this.song.speed;for(this.complete=15;e;){e.initialize();e.channel=this.mixer.channels[e.index];e.patternPos=this.song.tracks[e.index][0];b=e.synth;for(f=b+64;b<f;++b)this.mixer.memory[b]=0;e=e.next}}},loader:{value:function(b){for(var f,e,g,d,c,a,h,i,j,k;16>b.position;)if(h=b.readUshort(),b.position+=2,20218!=h)return;for(;1024>b.position;)if(h=b.readUshort(),4666==h)b.position+=2,h=b.readUshort(),
45057==h&&(b.position-=4,e=b.position+b.readUshort()-2197);else if(8522==h&&(b.position+=2,h=b.readUshort(),18426==h)){f=b.position+b.readShort();this.version=1;break}if(this.version){b.position=e+2210;a=b.readUint();b.position=f+a;this.samples=[];for(a=2147483647;a>b.position;){if(h=b.readUint()){if(h<b.position||h>=b.length){b.position-=4;break}h<a&&(a=f+h)}d=Object.create(null,{pointer:{value:0,writable:!0},loopPtr:{value:0,writable:!0},length:{value:0,writable:!0},relative:{value:0,writable:!0},
type:{value:0,writable:!0},synchro:{value:0,writable:!0},envelopeVol:{value:0,writable:!0},attackSpeed:{value:0,writable:!0},attackVol:{value:0,writable:!0},decaySpeed:{value:0,writable:!0},decayVol:{value:0,writable:!0},sustainTime:{value:0,writable:!0},releaseSpeed:{value:0,writable:!0},releaseVol:{value:0,writable:!0},arpeggio:{value:null,writable:!0},arpeggioLimit:{value:0,writable:!0},arpeggioSpeed:{value:0,writable:!0},vibratoDelay:{value:0,writable:!0},vibratoDepth:{value:0,writable:!0},vibratoSpeed:{value:0,
writable:!0},pulseCounter:{value:0,writable:!0},pulseDelay:{value:0,writable:!0},pulsePosL:{value:0,writable:!0},pulsePosH:{value:0,writable:!0},pulseSpeed:{value:0,writable:!0},pulseRateNeg:{value:0,writable:!0},pulseRatePos:{value:0,writable:!0},blendCounter:{value:0,writable:!0},blendDelay:{value:0,writable:!0},blendRate:{value:0,writable:!0}});d.pointer=h;d.loopPtr=b.readShort();d.length=b.readUshort()<<1;d.relative=b.readUshort();d.vibratoDelay=b.readUbyte();b.position++;d.vibratoSpeed=b.readUbyte();
d.vibratoDepth=b.readUbyte();d.envelopeVol=b.readUbyte();d.attackSpeed=b.readUbyte();d.attackVol=b.readUbyte();d.decaySpeed=b.readUbyte();d.decayVol=b.readUbyte();d.sustainTime=b.readUbyte();d.releaseSpeed=b.readUbyte();d.releaseVol=b.readUbyte();d.arpeggio=new Int8Array(16);for(g=0;16>g;++g)d.arpeggio[g]=b.readByte();d.arpeggioSpeed=b.readUbyte();d.type=b.readByte();d.pulseRateNeg=b.readByte();d.pulseRatePos=b.readUbyte();d.pulseSpeed=b.readUbyte();d.pulsePosL=b.readUbyte();d.pulsePosH=b.readUbyte();
d.pulseDelay=b.readUbyte();d.synchro=b.readUbyte();d.blendRate=b.readUbyte();d.blendDelay=b.readUbyte();d.pulseCounter=b.readUbyte();d.blendCounter=b.readUbyte();d.arpeggioLimit=b.readUbyte();b.position+=12;this.samples.push(d);if(!b.bytesAvailable)break}if(2147483647!=a){this.mixer.store(b,b.length-a);c=this.samples.length;for(g=0;g<c;++g)d=this.samples[g],d.pointer&&(d.pointer-=f+a)}a=this.mixer.memory.length;this.mixer.memory.length+=256;this.mixer.loopLen=100;for(g=0;4>g;++g)this.voices[g].synth=
a,a+=64;b.position=e+2210;c=b.readUint();a=b.readUint();b.position=f+a;this.patterns=ByteArray(new ArrayBuffer(c-a));b.readBytes(this.patterns,0,c-a);a+=f;b.position=e+2197;this.lastSong=c=b.readUbyte();this.songs=[];this.songs.length=++c;f=e+2830;k=a-f;for(g=a=0;g<c;++g){j=Object.create(null,{speed:{value:0,writable:!0},length:{value:0,writable:!0},tracks:{value:[],writable:!0}});j.tracks=[];for(d=0;4>d;++d){b.position=f+a;h=b.readUshort();i=3==d&&g==c-1?k:b.readUshort();i=i-h>>1;i>j.length&&(j.length=
i);j.tracks[d]=new Uint32Array(i);b.position=f+h;for(h=0;h<i;++h)j.tracks[d][h]=b.readUshort();a+=2}b.position=e+2199+g;j.speed=b.readUbyte();this.songs[g]=j}b.clear()}}},process:{value:function(){for(var b,f,e,g,d,c,a=this.voices[3];a;){b=a.channel;d=0;do if(this.patterns.position=a.patternPos,c=a.sample,this.sampFlag=0,a.busy||(a.busy=1,0==c.loopPtr?(b.pointer=this.mixer.loopPtr,b.length=this.mixer.loopLen):0<c.loopPtr&&(b.pointer=c.type?a.synth:c.pointer+c.loopPtr,b.length=c.length-c.loopPtr)),
0==--a.tick)for(d=2;1<d;)if(e=this.patterns.readByte(),0>e)switch(e){case -125:a.sample=c=this.samples[this.patterns.readUbyte()];this.sampFlag=1;a.patternPos=this.patterns.position;break;case -126:this.speed=this.patterns.readUbyte();a.patternPos=this.patterns.position;break;case -127:e=c?c.relative:428;a.portaSpeed=this.patterns.readUbyte()*this.speed;a.portaNote=this.patterns.readUbyte();a.portaLimit=l[a.portaNote]*e>>10;a.portamento=0;a.portaDelay=this.patterns.readUbyte()*this.speed;a.portaFlag=
1;a.patternPos=this.patterns.position;break;case -124:b.enabled=0;a.tick=this.speed;a.busy=1;a.patternPos=this.patterns.position;d=0;break;case -128:for(a.trackPos++;;)if(e=this.song.tracks[a.index][a.trackPos],65535==e)this.mixer.complete=1;else if(32767<e)a.trackPos=(e^32768)>>1,this.loopSong||(this.complete&=~a.bitFlag,this.complete||(this.mixer.complete=1));else{a.patternPos=e;d=a.tick=1;break}break;default:a.tick=this.speed*-e,a.patternPos=this.patterns.position,d=0}else{d=0;a.patternPos=this.patterns.position;
a.note=e;a.arpeggioPos=0;a.vibratoFlag=-1;a.vibrato=0;a.arpeggioSpeed=c.arpeggioSpeed;a.vibratoDelay=c.vibratoDelay;a.vibratoSpeed=c.vibratoSpeed;a.vibratoDepth=c.vibratoDepth;if(1==c.type){if(this.sampFlag||c.synchro&2){a.pulseCounter=c.pulseCounter;a.pulseDelay=c.pulseDelay;a.pulseDir=0;a.pulsePos=c.pulsePosL;a.pulseSpeed=c.pulseSpeed;f=a.synth;for(g=f+c.pulsePosL;f<g;++f)this.mixer.memory[f]=c.pulseRateNeg;for(g+=c.length-c.pulsePosL;f<g;++f)this.mixer.memory[f]=c.pulseRatePos}b.pointer=a.synth}else if(2==
c.type){a.blendCounter=c.blendCounter;a.blendDelay=c.blendDelay;a.blendDir=0;a.blendPos=1;f=c.pointer;e=a.synth;for(g=f+31;f<g;++f)this.mixer.memory[e++]=this.mixer.memory[f];b.pointer=a.synth}else b.pointer=c.pointer;a.tick=this.speed;a.busy=0;a.period=l[a.note]*c.relative>>10;a.volume=0;a.envelopePos=0;a.sustainTime=c.sustainTime;b.length=c.length;b.period=a.period;b.volume=0;b.enabled=1;a.portaFlag&&!a.portamento&&(a.portamento=a.period,a.portaCounter=1,a.portaPeriod=a.portaLimit-a.period)}else 1==
a.tick&&(e=this.patterns.readAt(a.patternPos)-160&255,127<e&&(b.enabled=0));while(0<d);if(b.enabled){e=a.note+c.arpeggio[a.arpeggioPos];0==--a.arpeggioSpeed&&(a.arpeggioSpeed=c.arpeggioSpeed,++a.arpeggioPos==c.arpeggioLimit&&(a.arpeggioPos=0));a.period=l[e]*c.relative>>10;a.portaFlag&&(a.portaDelay?a.portaDelay--:(a.period+=a.portaCounter*a.portaPeriod/a.portaSpeed,++a.portaCounter>a.portaSpeed&&(a.note=a.portaNote,a.portaFlag=0)));a.vibratoDelay?a.vibratoDelay--:a.vibratoFlag&&(0>a.vibratoFlag?(a.vibrato+=
a.vibratoSpeed,a.vibrato==a.vibratoDepth&&(a.vibratoFlag^=2147483648)):(a.vibrato-=a.vibratoSpeed,0==a.vibrato&&(a.vibratoFlag^=2147483648)),0==a.vibrato&&(a.vibratoFlag^=1),a.period=a.vibratoFlag&1?a.period+a.vibrato:a.period-a.vibrato);b.period=a.period;switch(a.envelopePos){case 0:a.volume+=c.attackSpeed;a.volume>=c.attackVol&&(a.volume=c.attackVol,a.envelopePos=1);break;case 1:a.volume-=c.decaySpeed;a.volume<=c.decayVol&&(a.volume=c.decayVol,a.envelopePos=2);break;case 2:a.sustainTime?a.sustainTime--:
a.envelopePos=3;break;case 3:a.volume-=c.releaseSpeed,a.volume<=c.releaseVol&&(a.volume=c.releaseVol,a.envelopePos=4)}e=c.envelopeVol<<12;e>>=8;e>>=4;e*=a.volume;e>>=8;e>>=1;b.volume=e;if(1==c.type)if(a.pulseDelay)a.pulseDelay--;else if(a.pulseSpeed)a.pulseSpeed--;else{if(a.pulseCounter||!(c.synchro&1)){a.pulseSpeed=c.pulseSpeed;if(a.pulseDir&4)for(;;){if(a.pulsePos>=c.pulsePosL){d=1;break}a.pulseDir&=-5;a.pulsePos++;a.pulseCounter--;if(a.pulsePos<=c.pulsePosH){d=2;break}a.pulseDir|=4;a.pulsePos--;
a.pulseCounter--}else for(;;){if(a.pulsePos<=c.pulsePosH){d=2;break}a.pulseDir|=4;a.pulsePos--;a.pulseCounter--;if(a.pulsePos>=c.pulsePosL){d=1;break}a.pulseDir&=-5;a.pulsePos++;a.pulseCounter++}b=a.synth+a.pulsePos;1==d?(this.mixer.memory[b]=c.pulseRatePos,a.pulsePos--):(this.mixer.memory[b]=c.pulseRateNeg,a.pulsePos++)}}else if(2==c.type)if(a.blendDelay)a.blendDelay--;else if(a.blendCounter||!(c.synchro&4)){a.blendDir?1!=a.blendPos?a.blendPos--:(a.blendDir^=1,a.blendCounter--):a.blendPos!=c.blendRate<<
1?a.blendPos++:(a.blendDir^=1,a.blendCounter--);f=c.pointer;g=f+31;for(b=g+1;f<g;++f)e=a.blendPos*this.mixer.memory[b++]>>c.blendRate,this.mixer.memory[b++]=e+this.mixer.memory[f]}}a=a.next}}}});i.voices[3]=k(3,8);i.voices[3].next=i.voices[2]=k(2,4);i.voices[2].next=i.voices[1]=k(1,2);i.voices[1].next=i.voices[0]=k(0,1);return Object.seal(i)}})();