/*
  Flod JS 2.0
  2012/04/01
  Christian Corti
  Neoart Costa Rica

  Last Update: Flod JS 2.0 - 2012/03/26

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function i(h){return Object.create(null,{index:{value:h,writable:!0},next:{value:null,writable:!0},channel:{value:null,writable:!0},enabled:{value:0,writable:!0},cosoCounter:{value:0,writable:!0},cosoSpeed:{value:0,writable:!0},trackPtr:{value:0,writable:!0},trackPos:{value:0,writable:!0},trackTransp:{value:0,writable:!0},patternPtr:{value:0,writable:!0},patternPos:{value:0,writable:!0},frqseqPtr:{value:0,writable:!0},frqseqPos:{value:0,writable:!0},volseqPtr:{value:0,writable:!0},volseqPos:{value:0,
writable:!0},sample:{value:0,writable:!0},loopPtr:{value:0,writable:!0},repeat:{value:0,writable:!0},tick:{value:0,writable:!0},note:{value:0,writable:!0},transpose:{value:0,writable:!0},info:{value:0,writable:!0},infoPrev:{value:0,writable:!0},volume:{value:0,writable:!0},volCounter:{value:0,writable:!0},volSpeed:{value:0,writable:!0},volSustain:{value:0,writable:!0},volTransp:{value:0,writable:!0},volFade:{value:0,writable:!0},portaDelta:{value:0,writable:!0},vibrato:{value:0,writable:!0},vibDelay:{value:0,
writable:!0},vibDelta:{value:0,writable:!0},vibDepth:{value:0,writable:!0},vibSpeed:{value:0,writable:!0},slide:{value:0,writable:!0},sldActive:{value:0,writable:!0},sldDone:{value:0,writable:!0},sldCounter:{value:0,writable:!0},sldSpeed:{value:0,writable:!0},sldDelta:{value:0,writable:!0},sldPointer:{value:0,writable:!0},sldLen:{value:0,writable:!0},sldEnd:{value:0,writable:!0},sldLoopPtr:{value:0,writable:!0},initialize:{value:function(){this.channel=null;this.trackPtr=this.cosoSpeed=this.cosoCounter=
this.enabled=0;this.trackPos=12;this.volseqPos=this.volseqPtr=this.frqseqPos=this.frqseqPtr=this.patternPos=this.patternPtr=this.trackTransp=0;this.sample=-1;this.volume=this.infoPrev=this.info=this.transpose=this.note=this.tick=this.repeat=this.loopPtr=0;this.volSpeed=this.volCounter=1;this.volTransp=this.volSustain=0;this.volFade=100;this.sldLoopPtr=this.sldEnd=this.sldLen=this.sldPointer=this.sldDelta=this.sldSpeed=this.sldCounter=this.sldDone=this.sldActive=this.slide=this.vibSpeed=this.vibDepth=
this.vibDelta=this.vibDelay=this.vibrato=this.portaDelta=0}}})}var j=[1712,1616,1524,1440,1356,1280,1208,1140,1076,1016,960,906,856,808,762,720,678,640,604,570,538,508,480,453,428,404,381,360,339,320,302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,113,113,113,113,113,113,113,113,113,113,113,113,113,3424,3232,3048,2880,2712,2560,2416,2280,2152,2032,1920,1812,6848,6464,6096,5760,5424,5120,4832,4560,4304,4064,3840,3624];window.neoart.JHPlayer=function(h){h=AmigaPlayer(h);Object.defineProperties(h,
{id:{value:"JHPlayer"},songs:{value:[],writable:!0},samples:{value:[],writable:!0},stream:{value:null,writable:!0},base:{value:0,writable:!0},patterns:{value:0,writable:!0},patternLen:{value:0,writable:!0},periods:{value:0,writable:!0},frqseqs:{value:0,writable:!0},volseqs:{value:0,writable:!0},samplesData:{value:0,writable:!0},song:{value:null,writable:!0},voices:{value:[],writable:!0},coso:{value:0,writable:!0},variant:{value:0,writable:!0},initialize:{value:function(){var c=this.voices[0];this.reset();
this.song=this.songs[this.playSong];this.speed=this.song.speed;for(this.tick=this.coso||1<this.variant?1:this.speed;c;)c.initialize(),c.channel=this.mixer.channels[c.index],c.trackPtr=this.song.pointer+3*c.index,this.coso?(c.trackPos=0,c.patternPos=8):(this.stream.position=c.trackPtr,c.patternPtr=this.patterns+this.stream.readUbyte()*this.patternLen,c.trackTransp=this.stream.readByte(),c.volTransp=this.stream.readByte(),c.frqseqPtr=this.base,c.volseqPtr=this.base),c=c.next}},loader:{value:function(c){var d=0,
e,g,f,b,a,h;this.base=this.periods=0;if(this.coso="COSO"==c.readString(4)){for(e=0;7>e;++e)d+=c.readInt();16942==d&&(c.position=47,d+=c.readUbyte());switch(d){case 22666:case 18842:case 30012:case 22466:case 3546:this.variant=1;break;case 16948:case 18332:case 13698:this.variant=2;break;case 18546:case 13926:case 8760:case 17242:case 11394:case 14494:case 14392:case 13576:case 6520:this.variant=3;break;default:this.variant=4}this.version=2;c.position=4;this.frqseqs=c.readUint();this.volseqs=c.readUint();
this.patterns=c.readUint();h=c.readUint();a=c.readUint();d=c.readUint();this.samplesData=c.readUint();c.position=0;c.writeInt(16777216);c.writeInt(225);c.writeShort(65535);f=(this.samplesData-d)/10-1;this.lastSong=(d-a)/6}else{for(;12<c.bytesAvailable;)switch(d=c.readUshort(),d){case 576:d=c.readUshort();127==d&&(c.position+=2,this.periods=c.position+c.readUshort());break;case 28674:case 28675:this.channels=d&255;d=c.readUshort();30208==d&&(d=c.readUshort());16890==d&&(c.position+=4,this.base=c.position+
c.readUshort());break;case 21574:d=c.readUshort(),19800==d&&(g=c.position-4,c.position=c.length)}if(!g||!this.base||!this.periods)return;this.version=1;c.position=g+4;this.frqseqs=e=g+32;d=c.readUshort();this.volseqs=e+=++d<<6;d=c.readUshort();this.patterns=e+=++d<<6;d=c.readUshort();c.position+=2;this.patternLen=c.readUshort();h=e+=++d*this.patternLen;c.position-=4;d=c.readUshort();a=e+=12*++d;c.position=g+16;this.lastSong=c.readUshort();d=e+=6*++this.lastSong;f=c.readUshort();this.samplesData=e+
30*f}c.position=d;this.samples=[];for(e=d=0;e<f;++e)b=AmigaSample(),this.coso||(b.name=c.readString(18)),b.pointer=c.readUint(),b.length=c.readUshort()<<1,this.coso||(b.volume=c.readUshort()),b.loopPtr=c.readUshort()+b.pointer,b.repeat=c.readUshort()<<1,b.loopPtr&1&&b.loopPtr--,d+=b.length,this.samples[e]=b;c.position=this.samplesData;this.mixer.store(c,d);c.position=a;this.songs=[];for(e=d=0;e<this.lastSong;++e)f=Object.create(null,{pointer:{value:0,writable:!0},speed:{value:0,writable:!0},length:{value:0,
writable:!0}}),f.pointer=c.readUshort(),f.length=c.readUshort()-f.pointer+1,f.speed=c.readUshort(),f.pointer=12*f.pointer+h,f.length*=12,12<f.length&&(this.songs[d++]=f);this.lastSong=this.songs.length-1;if(!this.coso){c.position=0;for(this.variant=1;c.position<g;)if(d=c.readUshort(),45116==d||3072==d){if(d=c.readUshort(),229==d||230==d||233==d){this.variant=2;break}}else if(20219==d){this.variant=3;break}}this.stream=c}},process:{value:function(){var c,d,e,g,f,b,a=this.voices[0];if(0==--this.tick){for(this.tick=
this.speed;a;){c=a.channel;if(this.coso){if(0>--a.cosoCounter){a.cosoCounter=a.cosoSpeed;do{this.stream.position=a.patternPos;do if(d=0,b=this.stream.readByte(),-1==b)a.trackPos==this.song.length&&(a.trackPos=0,this.mixer.complete=1),this.stream.position=a.trackPtr+a.trackPos,b=this.stream.readUbyte(),a.trackTransp=this.stream.readByte(),e=this.stream.readAt(this.stream.position),3<this.variant&&127<e?(g=e>>4&15,e&=15,15==g?(g=100,e&&(g=15-e+1,e=g<<=1,g<<=1,g+=e),a.volFade=g):8==g?this.mixer.complete=
1:14==g&&(this.speed=e)):a.volTransp=this.stream.readByte(),this.stream.position=this.patterns+(b<<1),a.patternPos=this.stream.readUshort(),a.trackPos+=12,d=1;else if(-2==b)a.cosoCounter=a.cosoSpeed=this.stream.readUbyte(),d=3;else if(-3==b)a.cosoCounter=a.cosoSpeed=this.stream.readUbyte(),a.patternPos=this.stream.position;else if(a.note=b,a.info=this.stream.readByte(),a.info&224&&(a.infoPrev=this.stream.readByte()),a.patternPos=this.stream.position,a.portaDelta=0,0<=b)if(1==this.variant&&(c.enabled=
0),b=(a.info&31)+a.volTransp,this.stream.position=this.volseqs+(b<<1),this.stream.position=this.stream.readUshort(),a.volCounter=a.volSpeed=this.stream.readUbyte(),a.volSustain=0,b=this.stream.readByte(),a.vibSpeed=this.stream.readByte(),a.vibrato=64,a.vibDepth=a.vibDelta=this.stream.readByte(),a.vibDelay=this.stream.readUbyte(),a.volseqPtr=this.stream.position,a.volseqPos=0,-128!=b)1<this.variant&&a.info&64&&(b=a.infoPrev),this.stream.position=this.frqseqs+(b<<1),a.frqseqPtr=this.stream.readUshort(),
a.frqseqPos=0,a.tick=0;while(2<d)}while(0<d)}}else{this.stream.position=a.patternPtr+a.patternPos;b=this.stream.readByte();if(a.patternPos==this.patternLen||1==(b&127))a.trackPos==this.song.length&&(a.trackPos=0,this.mixer.complete=1),this.stream.position=a.trackPtr+a.trackPos,b=this.stream.readUbyte(),a.trackTransp=this.stream.readByte(),a.volTransp=this.stream.readByte(),-128==a.volTransp&&(this.mixer.complete=1),a.patternPtr=this.patterns+b*this.patternLen,a.patternPos=0,a.trackPos+=12,this.stream.position=
a.patternPtr,b=this.stream.readByte();if(b&127&&(a.note=b&127,a.portaDelta=0,e=this.stream.position,a.patternPos||(this.stream.position+=this.patternLen),this.stream.position-=2,a.infoPrev=this.stream.readByte(),this.stream.position=e,a.info=this.stream.readByte(),0<=b))1==this.variant&&(c.enabled=0),b=(a.info&31)+a.volTransp,this.stream.position=this.volseqs+(b<<6),a.volCounter=a.volSpeed=this.stream.readUbyte(),a.volSustain=0,b=this.stream.readByte(),a.vibSpeed=this.stream.readByte(),a.vibrato=
64,a.vibDepth=a.vibDelta=this.stream.readByte(),a.vibDelay=this.stream.readUbyte(),a.volseqPtr=this.stream.position,a.volseqPos=0,1<this.variant&&a.info&64&&(b=a.infoPrev),a.frqseqPtr=this.frqseqs+(b<<6),a.frqseqPos=0,a.tick=0;a.patternPos+=2}a=a.next}a=this.voices[0]}for(;a;){c=a.channel;a.enabled=0;do if(d=0,a.tick)a.tick--;else{this.stream.position=a.frqseqPtr+a.frqseqPos;do{b=this.stream.readByte();if(-31==b)break;d=3;3==this.variant&&this.coso&&(-27==b?b=-30:-26==b&&(b=-28));switch(b){case -32:a.frqseqPos=
this.stream.readUbyte()&63;this.stream.position=a.frqseqPtr+a.frqseqPos;break;case -30:f=this.samples[this.stream.readUbyte()];a.sample=-1;a.loopPtr=f.loopPtr;a.repeat=f.repeat;a.enabled=1;c.enabled=0;c.pointer=f.pointer;c.length=f.length;a.volseqPos=0;a.volCounter=1;a.slide=0;a.frqseqPos+=2;break;case -29:a.vibSpeed=this.stream.readByte();a.vibDepth=this.stream.readByte();a.frqseqPos+=3;break;case -28:f=this.samples[this.stream.readUbyte()];a.loopPtr=f.loopPtr;a.repeat=f.repeat;c.pointer=f.pointer;
c.length=f.length;a.slide=0;a.frqseqPos+=2;break;case -27:if(2>this.variant)break;f=this.samples[this.stream.readUbyte()];c.enabled=0;a.enabled=1;2==this.variant?(e=this.stream.readUbyte()*f.length,a.loopPtr=f.loopPtr+e,a.repeat=f.repeat,c.pointer=f.pointer+e,c.length=f.length,a.frqseqPos+=3):(a.sldPointer=f.pointer,a.sldEnd=f.pointer+f.length,b=this.stream.readUshort(),a.sldLoopPtr=65535==b?f.length:b<<1,a.sldLen=this.stream.readUshort()<<1,a.sldDelta=this.stream.readShort()<<1,a.sldActive=0,a.sldCounter=
0,a.sldSpeed=this.stream.readUbyte(),a.slide=1,a.sldDone=0,a.frqseqPos+=9);a.volseqPos=0;a.volCounter=1;break;case -26:if(3>this.variant)break;a.sldLen=this.stream.readUshort()<<1;a.sldDelta=this.stream.readShort()<<1;a.sldActive=0;a.sldCounter=0;a.sldSpeed=this.stream.readUbyte();a.sldDone=0;a.frqseqPos+=6;break;case -25:1==this.variant?(a.frqseqPtr=this.frqseqs+(this.stream.readUbyte()<<6),a.frqseqPos=0,this.stream.position=a.frqseqPtr,d=3):(b=this.stream.readUbyte(),b!=a.sample&&(f=this.samples[b],
a.sample=b,a.loopPtr=f.loopPtr,a.repeat=f.repeat,a.enabled=1,c.enabled=0,c.pointer=f.pointer,c.length=f.length),a.volseqPos=0,a.volCounter=1,a.slide=0,a.frqseqPos+=2);break;case -24:a.tick=this.stream.readUbyte();a.frqseqPos+=2;d=1;break;case -23:if(2>this.variant)break;f=this.samples[this.stream.readUbyte()];a.sample=-1;a.enabled=1;g=this.stream.readUbyte();e=this.stream.position;c.enabled=0;this.stream.position=this.samplesData+f.pointer+4;b=24*this.stream.readUshort()+(this.stream.readUshort()<<
2);this.stream.position+=24*g;a.loopPtr=this.stream.readUint()&4294967294;c.length=(this.stream.readUint()&4294967294)-a.loopPtr;a.loopPtr+=f.pointer+b+8;c.pointer=a.loopPtr;a.repeat=2;this.stream.position=e;e=a.loopPtr+1;this.mixer.memory[e]=this.mixer.memory[a.loopPtr];a.volseqPos=0;a.volCounter=1;a.slide=0;a.frqseqPos+=3;break;default:a.transpose=b,a.frqseqPos++,d=0}}while(2<d)}while(0<d);a.slide&&!a.sldDone&&0>--a.sldCounter&&(a.sldCounter=a.sldSpeed,a.sldActive?(b=a.sldLoopPtr+a.sldDelta,0>b?
(a.sldDone=1,b=a.sldLoopPtr-a.sldDelta):(e=a.sldPointer+a.sldLen+b,e>a.sldEnd&&(a.sldDone=1,b=a.sldLoopPtr-a.sldDelta)),a.sldLoopPtr=b):a.sldActive=1,a.loopPtr=a.sldPointer+a.sldLoopPtr,a.repeat=a.sldLen,c.pointer=a.loopPtr,c.length=a.repeat);do if(d=0,a.volSustain)a.volSustain--;else{if(--a.volCounter)break;a.volCounter=a.volSpeed;do{this.stream.position=a.volseqPtr+a.volseqPos;b=this.stream.readByte();if(-25>=b&&-31<=b)break;switch(b){case -24:a.volSustain=this.stream.readUbyte();a.volseqPos+=2;
d=1;break;case -32:a.volseqPos=(this.stream.readUbyte()&63)-5;d=3;break;default:a.volume=b,a.volseqPos++,d=0}}while(2<d)}while(0<d);b=a.transpose;0<=b&&(b+=a.note+a.trackTransp);b&=127;this.coso?(83<b&&(b=0),d=j[b],b<<=1):(b<<=1,this.stream.position=this.periods+b,d=this.stream.readUshort());if(a.vibDelay)a.vibDelay--;else if(3<this.variant)a.vibrato&32?(b=a.vibDelta+a.vibSpeed,b>a.vibDepth&&(a.vibrato&=-33,b=a.vibDepth)):(b=a.vibDelta-a.vibSpeed,0>b&&(a.vibrato|=32,b=0)),a.vibDelta=b,b=(b-(a.vibDepth>>
1))*d,d+=b>>10;else if(2<this.variant)b=a.vibSpeed,0>b&&(b&=127,a.vibrato^=1),a.vibrato&1||(a.vibrato&32?(a.vibDelta+=b,e=a.vibDepth<<1,a.vibDelta>e&&(a.vibrato&=-33,a.vibDelta=e)):(a.vibDelta-=b,0>a.vibDelta&&(a.vibrato|=32,a.vibDelta=0))),d+=b-a.vibDepth;else{if(0<=a.vibrato||!(a.vibrato&1))a.vibrato&32?(a.vibDelta+=a.vibSpeed,e=a.vibDepth<<1,a.vibDelta>=e&&(a.vibrato&=-33,a.vibDelta=e)):(a.vibDelta-=a.vibSpeed,0>a.vibDelta&&(a.vibrato|=32,a.vibDelta=0));if(e=a.vibDelta-a.vibDepth){for(b+=160;256>
b;)e+=e,b+=24;d+=e}}3>this.variant&&(a.vibrato^=1);a.info&32&&(b=a.infoPrev,3<this.variant?0>b?(a.portaDelta+=-b,b=a.portaDelta*d,d+=b>>10):(a.portaDelta+=b,b=a.portaDelta*d,d-=b>>10):0>b?(a.portaDelta+=-b<<11,d+=a.portaDelta>>16):(a.portaDelta+=b<<11,d-=a.portaDelta>>16));b=3<this.variant?a.volFade*a.volume/100:a.volume;c.period=d;c.volume=b;a.enabled&&(c.enabled=1,c.pointer=a.loopPtr,c.length=a.repeat);a=a.next}}}});h.voices[0]=i(0);h.voices[0].next=h.voices[1]=i(1);h.voices[1].next=h.voices[2]=
i(2);h.voices[2].next=h.voices[3]=i(3);return Object.seal(h)}})();