/*
  JavaScript Flod 1.0
  2011/11/30
  Christian Corti
  Neoart Costa Rica

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 	OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 	LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  This work is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to
  Creative Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
*/
(function(){function j(h){return Object.create(null,{index:{value:h,writable:!0},next:{value:null,writable:!0},step:{value:null,writable:!0},row:{value:null,writable:!0},instr:{value:null,writable:!0},sample:{value:null,writable:!0},enabled:{value:0,writable:!0},pattern:{value:0,writable:!0},instrument:{value:0,writable:!0},note:{value:0,writable:!0},period:{value:0,writable:!0},volume:{value:0,writable:!0},original:{value:0,writable:!0},adsrPos:{value:0,writable:!0},sustainCtr:{value:0,writable:!0},
pitchBend:{value:0,writable:!0},pitchBendCtr:{value:0,writable:!0},noteSlideTo:{value:0,writable:!0},noteSlideSpeed:{value:0,writable:!0},waveCtr:{value:0,writable:!0},wavePos:{value:0,writable:!0},arpeggioCtr:{value:0,writable:!0},arpeggioPos:{value:0,writable:!0},vibratoCtr:{value:0,writable:!0},vibratoPos:{value:0,writable:!0},timer:{value:0,writable:!0},initialize:{value:function(){this.sample=this.instr=this.row=this.step=null;this.timer=this.vibratoPos=this.vibratoCtr=this.arpeggioPos=this.arpeggioCtr=
this.wavePos=this.waveCtr=this.noteSlideSpeed=this.noteSlideTo=this.pitchBendCtr=this.pitchBend=this.sustainCtr=this.adsrPos=this.original=this.volume=this.period=this.note=this.instrument=this.pattern=this.enabled=0}}})}window.neoart.createS2Player=function(h){h=createAmigaPlayer(h);Object.defineProperties(h,{id:{value:"S2Player"},tracks:{value:[],writable:!0},patterns:{value:[],writable:!0},instruments:{value:[],writable:!0},samples:{value:[],writable:!0},arpeggios:{value:[],writable:!0},vibratos:{value:[],
writable:!0},waves:{value:[],writable:!0},length:{value:0,writable:!0},speedDef:{value:0,writable:!0},voices:{value:[],writable:!0},trackPos:{value:0,writable:!0},patternPos:{value:0,writable:!0},patternLen:{value:0,writable:!0},arpeggioFx:{value:[],writable:!0},arpeggioPos:{value:0,writable:!0},initialize:{value:function(){var b=this.voices[0];this.core_initialize();this.tick=this.timer=this.speedDef;this.patternPos=this.trackPos=0;for(this.patternLen=64;b;)b.initialize(),b.channel=this.mixer.channels[b.index],
b.instr=this.instruments[0],this.arpeggioFx[b.index]=0,b=b.next}},loader:{value:function(b){var c,d,e,f;e=0;var a,h=0,i,j,g;b.position=58;if("SIDMON II - THE MIDI VERSION"==b.readString(28)){b.position=2;this.length=b.readUnsignedByte();this.speedDef=b.readUnsignedByte();this.samples=[];this.samples.length=b.readUnsignedShort()>>6;b.position=14;f=b.readUnsignedInt();this.tracks=[];this.tracks.length=f;b.position=90;for(c=0;c<f;++c){a=this.createStep();a.pattern=b.readUnsignedByte();if(a.pattern>e)e=
a.pattern;this.tracks[c]=a}for(c=0;c<f;++c)a=this.tracks[c],a.transpose=b.readByte();for(c=0;c<f;++c)a=this.tracks[c],a.soundTranspose=b.readByte();a=b.position;b.position=26;f=b.readUnsignedInt()>>5;this.instruments=[];this.instruments.length=++f;b.position=a;this.instruments[0]=this.createInstrument();for(c=0;++c<f;)d=this.createInstrument(),d.wave=b.readUnsignedByte()<<4,d.waveLen=b.readUnsignedByte(),d.waveSpeed=b.readUnsignedByte(),d.waveDelay=b.readUnsignedByte(),d.arpeggio=b.readUnsignedByte()<<
4,d.arpeggioLen=b.readUnsignedByte(),d.arpeggioSpeed=b.readUnsignedByte(),d.arpeggioDelay=b.readUnsignedByte(),d.vibrato=b.readUnsignedByte(),d.vibratoLen=b.readUnsignedByte(),d.vibratoSpeed=b.readUnsignedByte(),d.vibratoDelay=b.readUnsignedByte(),d.pitchBend=b.readByte(),d.pitchBendDelay=b.readUnsignedByte(),b.readByte(),b.readByte(),d.attackMax=b.readUnsignedByte(),d.attackSpeed=b.readUnsignedByte(),d.decayMin=b.readUnsignedByte(),d.decaySpeed=b.readUnsignedByte(),d.sustain=b.readUnsignedByte(),
d.releaseMin=b.readUnsignedByte(),d.releaseSpeed=b.readUnsignedByte(),this.instruments[c]=d,b.position+=9;a=b.position;b.position=30;f=b.readUnsignedInt();this.waves=[];this.waves.length=f;b.position=a;for(c=0;c<f;++c)this.waves[c]=b.readUnsignedByte();a=b.position;b.position=34;f=b.readUnsignedInt();this.arpeggios=[];this.arpeggios.length=f;b.position=a;for(c=0;c<f;++c)this.arpeggios[c]=b.readByte();a=b.position;b.position=38;f=b.readUnsignedInt();this.vibratos=[];this.vibratos.length=f;b.position=
a;for(c=0;c<f;++c)this.vibratos[c]=b.readByte();f=this.samples.length;for(c=a=0;c<f;++c)d=this.createSample(),b.readUnsignedInt(),d.length=b.readUnsignedShort()<<1,d.loop=b.readUnsignedShort()<<1,d.repeat=b.readUnsignedShort()<<1,d.negStart=a+(b.readUnsignedShort()<<1),d.negLen=b.readUnsignedShort()<<1,d.negSpeed=b.readUnsignedShort(),d.negDir=b.readUnsignedShort(),d.negOffset=b.readShort(),d.negPos=b.readUnsignedInt(),d.negCtr=b.readUnsignedShort(),b.position+=6,d.name=b.readString(32),d.pointer=
a,d.loopPtr=a+d.loop,a+=d.length,this.samples[c]=d;j=a;f=++e;d=[];d.length=++e;for(c=0;c<f;++c)d[c]=b.readUnsignedShort();a=b.position;b.position=50;f=b.readUnsignedInt();this.patterns=[];b.position=a;e=1;for(c=0;c<f;++c)i=this.createRow(),g=b.readByte(),0==g?(i.effect=b.readByte(),i.param=b.readUnsignedByte(),c+=2):0>g?i.timer=~g:112>g?(i.note=g,g=b.readByte(),c++,0>g?i.timer=~g:112>g?(i.sample=g,g=b.readByte(),c++,0>g?i.timer=~g:(i.effect=g,i.param=b.readUnsignedByte(),c++)):(i.effect=g,i.param=
b.readUnsignedByte(),c++)):(i.effect=g,i.param=b.readUnsignedByte(),c++),this.patterns[h++]=i,a+d[e]==b.position&&(d[e++]=h);d[e]=this.patterns.length;0!=(b.position&1)&&b.position++;this.mixer.store(b,j);f=this.tracks.length;for(c=0;c<f;++c)a=this.tracks[c],a.pattern=d[a.pattern];this.length++;this.version=1}}},process:{value:function(){var b,c,d,e,f,a=this.voices[0];this.arpeggioPos=++this.arpeggioPos&3;if(++this.tick>=this.timer){for(this.tick=0;a;){b=a.channel;a.enabled=a.note=0;if(0==this.patternPos)a.step=
this.tracks[this.trackPos+a.index*this.length],a.pattern=a.step.pattern,a.timer=0;if(0>--a.timer&&(a.row=d=this.patterns[a.pattern++],a.timer=d.timer,d.note))a.enabled=1,a.note=d.note+a.step.transpose,b.enabled=0;a.pitchBend=0;if(a.note){a.waveCtr=a.sustainCtr=0;a.arpeggioCtr=a.arpeggioPos=0;a.vibratoCtr=a.vibratoPos=0;a.pitchBendCtr=a.noteSlideSpeed=0;a.adsrPos=4;a.volume=0;if(d.sample)a.instrument=d.sample,a.instr=this.instruments[a.instrument+a.step.soundTranspose],a.sample=this.samples[this.waves[a.instr.wave]];
a.original=a.note+this.arpeggios[a.instr.arpeggio];b.period=a.period=k[a.original];e=a.sample;b.pointer=e.pointer;b.length=e.length;b.enabled=a.enabled;b.pointer=e.loopPtr;b.length=e.repeat}a=a.next}if(++this.patternPos==this.patternLen&&(this.patternPos=0,++this.trackPos==this.length))this.trackPos=0,this.mixer.complete=1}for(a=this.voices[0];a;){if(a.sample&&(e=a.sample,!e.negToggle))if(e.negToggle=1,e.negCtr)e.negCtr=--e.negCtr&31;else{e.negCtr=e.negSpeed;if(0==e.negDir){a=a.next;continue}f=e.negStart=
e.negPos;this.mixer.memory[f]=~this.mixer.memory[f];e.negPos+=e.negOffset;f=e.negLen-1;if(0>e.negPos)2==e.negDir?e.negPos=f:(e.negOffset=~e.negOffset+1,e.negPos+=e.negOffset);else if(f<e.negPos)1==e.negDir?e.negPos=0:(e.negOffset=~e.negOffset+1,e.negPos+=e.negOffset)}a=a.next}for(a=this.voices[0];a;){if(a.sample)a.sample.negToggle=0;a=a.next}for(a=this.voices[0];a;){b=a.channel;c=a.instr;switch(a.adsrPos){case 4:a.volume+=c.attackSpeed;if(c.attackMax<=a.volume)a.volume=c.attackMax,a.adsrPos--;break;
case 3:if(0==c.decaySpeed)a.adsrPos--;else if(a.volume-=c.decaySpeed,c.decayMin>=a.volume)a.volume=c.decayMin,a.adsrPos--;break;case 2:a.sustainCtr==c.sustain?a.adsrPos--:a.sustainCtr--;break;case 1:if(a.volume-=c.releaseSpeed,c.releaseMin>=a.volume)a.volume=c.releaseMin,a.adsrPos--}b.volume=a.volume>>2;if(c.waveLen)a.waveCtr==c.waveDelay?(a.waveCtr=c.waveDelay-c.waveSpeed,a.wavePos==c.waveLen?a.wavePos=0:a.wavePos++,a.sample=e=this.samples[waves[c.wave+a.wavePos]],b.pointer=e.pointer,b.length=e.length):
a.waveCtr++;if(c.arpeggioLen)a.arpeggioCtr==c.arpeggioDelay?(a.arpeggioCtr=c.arpeggioDelay-c.arpeggioSpeed,a.arpeggioPos==c.arpeggioLen?a.arpeggioPos=0:a.arpeggioPos++,f=a.original+this.arpeggios[c.arpeggio+a.arpeggioPos],a.period=k[f]):a.arpeggioCtr++;d=a.row;if(0==this.tick)switch(d.effect){case 112:this.arpeggioFx[0]=d.param>>4;this.arpeggioFx[2]=d.param&15;f=a.original+this.arpeggioFx[this.arpeggioPos];a.period=k[f];break;case 113:a.pitchBend=~d.param+1;break;case 114:a.pitchBend=d.param;break;
case 115:if(0!=a.adsrPos)break;if(0!=a.instrument)a.volume=c.attackMax;a.volume+=d.param<<2;if(256<=a.volume)a.volume=-1;break;case 116:if(0!=a.adsrPos)break;if(0!=a.instrument)a.volume=c.attackMax;a.volume-=d.param<<2;if(0>a.volume)a.volume=0}switch(d.effect){case 117:c.attackMax=d.param;c.attackSpeed=d.param;break;case 118:this.patternLen=d.param;break;case 119:b.volume=d.param;a.volume=d.param<<2;if(255<=a.volume)a.volume=255;break;case 120:if(f=d.param&15)this.timer=f}if(c.vibratoLen)a.vibratoCtr==
c.vibratoDelay?(a.vibratoCtr=c.vibratoDelay-c.vibratoSpeed,a.vibratoPos==c.vibratoLen?a.vibratoPos=0:a.vibratoPos++,a.period+=this.vibratos[c.vibrato+a.vibratoPos]):a.vibratoCtr++;c.pitchBend&&(a.pitchBendCtr==c.pitchBendDelay?a.pitchBend+=c.pitchBend:a.pitchBendCtr++);if(d.param&&d.effect&&112>d.param)a.noteSlideTo=k[d.effect+a.step.transpose],f=d.param,0>a.noteSlideTo-a.period&&(f=~f+1),a.noteSlideSpeed=f;if(a.noteSlideTo&&a.noteSlideSpeed&&(a.period+=a.noteSlideSpeed,0>a.noteSlideSpeed&&a.period<
a.noteSlideTo||0<a.noteSlideSpeed&&a.period>a.noteSlideTo))a.noteSlideSpeed=0,a.period=a.noteSlideTo;a.period+=a.pitchBend;if(95>a.period)a.period=95;else if(5760<a.period)a.period=5760;b.period=a.period;a=a.next}}},createInstrument:{value:function(){return Object.create(null,{wave:{value:0,writable:!0},waveLen:{value:0,writable:!0},waveDelay:{value:0,writable:!0},waveSpeed:{value:0,writable:!0},arpeggio:{value:0,writable:!0},arpeggioLen:{value:0,writable:!0},arpeggioDelay:{value:0,writable:!0},arpeggioSpeed:{value:0,
writable:!0},vibrato:{value:0,writable:!0},vibratoLen:{value:0,writable:!0},vibratoDelay:{value:0,writable:!0},vibratoSpeed:{value:0,writable:!0},pitchBend:{value:0,writable:!0},pitchBendDelay:{value:0,writable:!0},attackMax:{value:0,writable:!0},attackSpeed:{value:0,writable:!0},decayMin:{value:0,writable:!0},decaySpeed:{value:0,writable:!0},sustain:{value:0,writable:!0},releaseMin:{value:0,writable:!0},releaseSpeed:{value:0,writable:!0}})}},createRow:{value:function(){var b=this.mixer.createRow();
Object.defineProperties(b,{timer:{value:0,writable:!0}});return b}},createSample:{value:function(){var b=this.mixer.createSample();Object.defineProperties(b,{negStart:{value:0,writable:!0},negLen:{value:0,writable:!0},negSpeed:{value:0,writable:!0},negDir:{value:0,writable:!0},negOffset:{value:0,writable:!0},negPos:{value:0,writable:!0},negCtr:{value:0,writable:!0},negToggle:{value:0,writable:!0}});return b}},createStep:{value:function(){return Object.create(null,{pattern:{value:0,writable:!0},soundTranspose:{value:0,
writable:!0},transpose:{value:0,writable:!0}})}}});h.voices[0]=j(0);h.voices[0].next=h.voices[1]=j(1);h.voices[1].next=h.voices[2]=j(2);h.voices[2].next=h.voices[3]=j(3);return Object.seal(h)};var k=[5760,5424,5120,4832,4560,4304,4064,3840,3616,3424,3232,3048,2880,2712,2560,2416,2280,2152,2032,1920,1808,1712,1616,1524,1440,1356,1280,1208,1140,1076,1016,960,904,856,808,762,720,678,640,604,570,538,508,480,453,428,404,381,360,339,320,302,285,269,254,240,226,214,202,190,180,170,160,151,143,135,127,120,
113,107,101,95]})();